### ISSUE TITLE
PHP Storm looses local history after installation

### ISSUE THREAD

**Issue by jmashore** [wakatime/jetbrains-wakatime#100]
Hello..
I am running Windows 10 Pro Version 1709, and using PHP Storm 2017.3.3
I recently installed the wakatime pluggin as outlined in the instructions.
Two things happened : I lost my local history and no new local history was being collected and I was no longer being warned about files on the server having been modified. (Tools->Deployment->Options->Notify of remote changes).
I uninstalled wakatime, rebooted and now local history is working but has lost any prior history that existed.

**Comment by alanhamlett** [comment]
Try turning on Debug Mode then restarting PhpStorm and watch your `idea.log` for errors:
https://github.com/wakatime/jetbrains-wakatime#troubleshooting

WakaTime listens for file saves with [beforeDocumentSaving](https://github.com/wakatime/jetbrains-wakatime/blob/master/src/com/wakatime/intellij/plugin/CustomSaveListener.java#L22) and file changes with [documentChanged](https://github.com/wakatime/jetbrains-wakatime/blob/master/src/com/wakatime/intellij/plugin/CustomDocumentListener.java#L26) event listeners. Maybe something there could be interfering with PhpStorm's local history feature.

**Comment by gandarez** [comment]
Is this still NOK @alanhamlett?
