### ISSUE TITLE
Offline Coding Does not Sync

### ISSUE THREAD

**Issue by mureithimaina** [wakatime/jetbrains-wakatime#101]
I have been coding offline through the long weekend, and the dashboard only counts for today when i was online, i use php storm

**Comment by alanhamlett** [comment]
Coding activity can take some time to sync, but two things to check are:

1. Are there any error messages in your `~/.wakatime.log` file from over the weekend.
2. Are there heartbeats saved in your local sqlite database `~/.wakatime.db`? To check, run `sqlite3 ~/.wakatime.db --echo "select count(*) from heartbeat_2"`.

**Comment by igorkovalchuk** [comment]
@alanhamlett FYI: Android Studio 3.1.3, WakaTime plugin 9.2.0 , Linux. It looks that it doesn't sync the offline coding time.

**Comment by igorkovalchuk** [comment]
@alanhamlett Oh, I am sorry - it have synchronized and now it shows me my time on the dashboard (but only on the second day).
