### ISSUE TITLE
Restricted WakaTime Python Directory

### ISSUE THREAD

**Issue by cbb330** [wakatime/jetbrains-wakatime#102]
On my enterprise machine, the AppData/Roaming directory has restricted execution access and because WakaTime uses python scripts in this directory, PyCharm fails to initialize WakaTime.

Is there anyway to move the AppData/Roaming/WakaTime folder to another location?

-Christian

**Comment by alanhamlett** [comment]
You can set a system environment variable `WAKATIME_HOME` pointing to a different folder. Does that work in your case?

**Comment by bjeorn** [comment]
This fixed it for me. Thanks!
