### ISSUE TITLE
Android Studio extension instructions are misleading

### ISSUE THREAD

**Issue by nickymarino** [wakatime/jetbrains-wakatime#104]
The [instructions](https://wakatime.com/android-studio) for installing the Android Studio extension should be updated to the following steps:

Step 1 --  Inside Android Studio, select `File` -> `Settings...` -> `Plugins` -> `Browse Repositories...`
Step 5 --  Go to `Tools` -> `WakaTime Settings`, enter your API key and click `Save`.

(These steps are current for Android Studio 3.1.2 on Windows 10)

**Comment by alanhamlett** [comment]
Updated the instructions with Windows specific menu. Thanks!
