### ISSUE TITLE
Building/Editing Plugin Configuration Issues

### ISSUE THREAD

**Issue by alichtman** [wakatime/jetbrains-wakatime#105]
I followed [these instructions](http://www.jetbrains.org/display/IJOS/Writing+Plug-ins) to configure the plugin development environment. 

I've cloned this plugin and tried to open it in IntelliJ IDEA CE 8.01 and the import statements are not being satisfied.

Different dependencies break based on which Module SDK I use, and I can only use one of the modules at a time.

With this SDK:
<img width="706" alt="image" src="https://user-images.githubusercontent.com/20600565/41495601-50b0a15a-70f8-11e8-8fef-9725aa843fbb.png">

![35343062_1716135605169305_2579435363726524416_n](https://user-images.githubusercontent.com/20600565/41495596-3c3429c2-70f8-11e8-857f-dc9678868726.png)

And with this one: 
<img width="710" alt="image" src="https://user-images.githubusercontent.com/20600565/41495602-5b34d1be-70f8-11e8-86f5-ea79e7d407f7.png">

![35078567_1712049328911266_3584464990960091136_n](https://user-images.githubusercontent.com/20600565/41495598-3dd1a228-70f8-11e8-80bf-deb1c83db253.png)

**Unsuccessful Fix Attempts**

+ [Plugin Development Guidelines](https://www.jetbrains.com/help/idea/plugin-development-guidelines.html#d394330e7)

+ [Configuring IntelliJ Platform Plugin SDK](https://www.jetbrains.com/help/idea/configuring-intellij-platform-plugin-sdk.html)

+ [SO Posts suggested creating a brand new plugin. Unsuccessful.](https://stackoverflow.com/questions/4481951/intellij-idea-jdk-configuration-on-mac-os/4482827#4482827)

**Next Steps?**

+ [Guide to Setting Up Environment](http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/setting_up_environment.html)

+ [Do I add wakatime to the plugins directory?](https://stackoverflow.com/questions/18278440/how-to-import-and-run-existing-plugins-from-intellij-community-edition-repo?rq=1)

**If you have any ideas for fixing this, that'd be much appreciated.**

**Comment by alanhamlett** [comment]
You need to configure the IntelliJ Platform SDK according to these instructions:
https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/setting_up_environment.html#configuring-intellij-platform-sdk

Then re-open the project and set the project's SDK to `IntelliJ Platform Plugin SDK`.

Let's leave this issue open until upgrading to Gradle or a setup script is available to do the above.

**Comment by gandarez** [comment]
Does that need to keep opened @alanhamlett?
