### ISSUE TITLE
Viewing the time elapsed for the day on a project right inside the IDE

### ISSUE THREAD

**Issue by oxysoft** [wakatime/jetbrains-wakatime#107]
I would suggest displaying it on the status bar of the editor with a toggle in the preferences for those who would rather not. I know it would be motivating for me to see my time go up as I am working. Simply refreshing the page on my Dashboard online has that effect for me, so having it straight inside the editor would be an excellent convenience feature I think that could be motivating for other people as well.

**Comment by russeg** [comment]
What is the status of this?

I just installed this on IDEA, and it was the first thing I searched for. Would also serve as an indicator that the plugin is working.

Similar to VSCODE would be sufficient. An icon and time on the status bar, and clicking it would go to web dashboard.

**Comment by JordanTranchina** [comment]
Hi @alanhamlett any update on the above? I tried to find the $WAKATIME_HOME/.wakatime.cfg file (as instructed here: https://github.com/wakatime/wakatime#configuring) but wasn't able to find it. Alternatively, do you know what console command I can run to see wakatime in the statusbar?

**Comment by WilliamStam** [comment]
this is definitely something i miss from VSCode now that im back on jetbrains products :(

**Comment by luckydonald** [comment]
Maybe like Darkyn's time tracker?
![](https://plugins.jetbrains.com/files/9286/screenshot_16595.png)
https://plugins.jetbrains.com/plugin/9286-darkyen-s-time-tracker

https://github.com/Darkyenus/DarkyenusTimeTracker/

**Comment by alanhamlett** [comment]
Added with v12.0.0.

**Comment by WilliamStam** [comment]
wow. thank you!

**Comment by JordanTranchina** [comment]
Thank you @alanhamlett!
