### ISSUE TITLE
Supports a tracking build times like a Xcode?

### ISSUE THREAD

**Issue by satoshun** [wakatime/jetbrains-wakatime#116]
Hi! I try a tracking build times. I'm so glad if you use this code as a reference.

https://github.com/satoshun-android-example/jetbrains-wakatime/commit/063223fbaeeb0e6234b312b6bef1f4760da754ca#diff-f36bd864ed525c2b1ba331e6ade3ab4aR8

**Comment by alanhamlett** [comment]
Implemented tracking build times in release v14.0.0.
