### ISSUE TITLE
A typo in the repository description

### ISSUE THREAD

**Issue by VadimKulagin** [wakatime/jetbrains-wakatime#117]
You have written `Gogland` instead of `GoLand` in the description of the repository:
> IntelliJ IDEA, PyCharm, RubyMine, PhpStorm, AppCode, AndroidStudio, Gogland, Rider, & WebStorm plugin for quantifying your coding. https://wakatime.com/intellij-idea

**Comment by alanhamlett** [comment]
Thanks!
