### ISSUE TITLE
Sometimes .wakatime-project is ignored

### ISSUE THREAD

**Issue by Hermesiss** [wakatime/jetbrains-wakatime#118]
Some of my activity on project ignores name in .wakatime-project and is displays in dashboard as solution name

**Comment by alanhamlett** [comment]
That's a bug where this block should be moved down:
https://github.com/wakatime/wakatime/blob/d11c64db2b9568d9914043dd16a201848a4bdf1d/wakatime/project.py#L52

I'll release a fix soon.

**Comment by alanhamlett** [comment]
Are you sure the solution project is new coding activity after creating the `.wakatime-project` file?

**Comment by Hermesiss** [comment]
@alanhamlett yes
my actions:
1. create this file with desired name in root folder for Unity project I never opened using any Wakatime plugins
1. open project in Unity with configured 
1. dashboard shows overridden name
1. open some script in Rider
1. dashboard now shows 1 min of solution project
1. all followed statistics appears in the right project

**Comment by alanhamlett** [comment]
Since this bug isn't related to Jetbrains IDEs I've moved this issue to wakatime/wakatime#169. Let's continue chatting there.

**Comment by alanhamlett** [comment]
Can you turn on debug mode in Rider, relaunch Rider, then tail your `idea.log` file and `~/.wakatime.log` file to look for any error messages? Here's info about finding your `idea.log` file:
https://github.com/wakatime/jetbrains-wakatime#troubleshooting

Maybe we find a file read error when opening `.wakatime-project` but let's see.

**Comment by Hermesiss** [comment]
forgot to enable debug mode on second machine, and found this strange record:
![image](https://user-images.githubusercontent.com/20972731/55003474-efc6b300-4ff1-11e9-85ef-ec7ca6e1c8d3.png)
it was tracked to completely different project

**Comment by Hermesiss** [comment]
![image](https://user-images.githubusercontent.com/20972731/55003690-4b913c00-4ff2-11e9-8008-a09007415c64.png)
I figured it out
1. open solution `D:/Foo/Foo.sln` with overridden project name `foo-override`
1. open any `*.cs` file (not solution!) from `D:/Bar/` **without** `.wakatime-project` at its root. It will open in same Rider window
1. it will try to open `D:/Bar/.wakatime-project`, there is none, so it will ask Rider for project name, which is `Foo`
1. Now we have record in dashbord about file e.g. `BarController.cs` in `Foo` project

**Comment by gandarez** [comment]
@alanhamlett I could reprocude the behaviour on my side also. What do you think to pass `--alternate-project` instead of `--project` and let the cli finds the correct project instead of the IDE? By doing it the cli will traverse the right folder of the opened file.

**Comment by ahmedosama94** [comment]
Facing the same (or a very similar) issue, it was working fine until recently. Now ALL the activity on WebStorm is ignoring the `.wakatime-project` file.

**Comment by gandarez** [comment]
Was that fixed by https://github.com/wakatime/jetbrains-wakatime/commit/a7533fdf2ff11f15b1d755ba32bfb046a08c9bbb @alanhamlett?

**Comment by alanhamlett** [comment]
Should be fixed now.
