### ISSUE TITLE
go.mod logged as Modula-2

### ISSUE THREAD

**Issue by tehsphinx** [wakatime/jetbrains-wakatime#119]
Working on `go.mod` should be logged as the language `Go`, not `Modula-2`.

Not sure it this is decided on the editor side or at wakatime. I am using it with `Goland IDE`.

**Comment by alanhamlett** [comment]
Implemented with wakatime/wakatime@4c4760a805f0d31667a98fbf4a81e6b359f55a9b and released in v10.8.2 of wakatime-cli. Restart your IDE and it will update with the fix.
