### ISSUE TITLE
Not seeing time logged on Wakatime dashboard

### ISSUE THREAD

**Issue by fluffynuts** [wakatime/jetbrains-wakatime#122]
I've seen a sharp decline, to zero of all coding time logged and presented on my dashboard.

I'm running the wakatime plugin in
- Rider
- WebStorm

I'm also not seeing coding time from VSCode (I know that's a separate project), which may speak to a larger issue. I'd appreciate any help getting to the bottom of this. I have enabled DEBUG mode in Rider, but I'm not seeing any logs created in my home folder -- there was previously a .wakatime.log, but it only had really old logs in it (months ago), so I deleted it, and I haven't seen it recreated.

OS: Windows 10

**Comment by alanhamlett** [comment]
Do you have any error messages related to WakaTime in Rider's `idea.log` file? Here's how to find that log file:
https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by fluffynuts** [comment]
I _think_ I may have found the culprit (would just like a day or two to confirm, since I found it late in the day):

Windows 10 build 1903 now ships with a `python.exe` which takes the user off to the store to get an installation of Python from there. I had previously installed from the store because I want to take advantage of automatic updates. My `python.exe` which used to be in the path had been replaced with this faux python, so all scripts (including, of course, wakatime cli) would effectively do nothing.

I was seeing periodic errors in vim / gvim which made me think it was something wrong with cli / thereabouts, hence why I went down this path of discovery. I can see 51 minutes logged against Rider today -- I just want to run for another day to confirm, and this can probably be closed out, with some kind of warning for others -- I'm not sure who else will end up getting the faux `python.exe` in their path!

**Comment by alanhamlett** [comment]
> Windows 10 build 1903 now ships with a python.exe which takes the user off to the store to get an installation of Python from there.

I didn't know about that! Yes we'll add a warning or hopefully detect this faux `python.exe` and prevent the plugin from using it.

**Comment by fluffynuts** [comment]
:+1:

I'ts pretty cool that python is being made more accessible -- it's a great language to learn because it provides a shallow entry but the sky's the limit.
It's just a pity that this helper got in the way. 
This *may* also be because I *think* I installed from the store when it was announced, but I *think* I was still on build 18-something, and the upgrade to 1903 only properly completed about a week ago -- which coincides with the dip in info.

I've also just seen logging this morning from 8 minutes with a project open, so I'm going to consider this resolved and I hope no-one else gets caught out by this (:
