### ISSUE TITLE
[help] How to use the IntelliJ built-in proxy with wakatime?

### ISSUE THREAD

**Issue by Yohandah** [wakatime/jetbrains-wakatime#125]
Hello,

I'm behind a corporate proxy, I configured it into IntelliJ and it works, But Wakatime doesn't seem to sync data anyways.

I've seen a "proxy" parameter into WakaTime settings, but it doesn't allow for a script or an auto-detect, why not use IntelliJ proxy parameters ? I have correctly set my API key, and when I open an external proxy (like fiddler), it works (but it's annoying).

![Capture](https://user-images.githubusercontent.com/15921402/66763512-3efa0580-eea8-11e9-8cdd-2038dfac2ea8.PNG)

![Capture2](https://user-images.githubusercontent.com/15921402/66763511-3e616f00-eea8-11e9-8599-4eed2f6fa370.PNG)

**Comment by alanhamlett** [comment]
Good idea, we would need the plugin to detect proxy settings from IntelliJ and pass that to wakatime-cli in the `--proxy` param.

**Comment by gandarez** [comment]
Is that a feature request still needed @alanhamlett?

**Comment by alanhamlett** [comment]
> Is that a feature request still needed @alanhamlett?

Yes, we still need to detect the proxy from the IDE and pass as `--proxy`:
https://github.com/wakatime/jetbrains-wakatime/blob/a7533fdf2ff11f15b1d755ba32bfb046a08c9bbb/src/com/wakatime/intellij/plugin/WakaTime.java#L394

**Comment by pjpv** [comment]
Why hasn't this issue been resolved? Currently, if I set a proxy in the IDE, the logs fail to update. However, using a proxy is essential for me.
