### ISSUE TITLE
[help] idea plugins invalid

### ISSUE THREAD

**Issue by huifer** [wakatime/jetbrains-wakatime#128]
- Information about my idea
```
IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 28, 2019
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 12
```
- No data record in the instrument cluster
![image](https://user-images.githubusercontent.com/26766909/70367489-5ae3bb80-18db-11ea-84f1-bbd8126bbd0f.png)

- Normal use on Windows

**Comment by alanhamlett** [comment]
Are there any error messages in your idea.log or wakatime.log files after turning on debug mode in the plugin?
