### ISSUE TITLE
cannot find .wakatime.log in debug mode

### ISSUE THREAD

**Issue by joechenrh** [wakatime/jetbrains-wakatime#140]
I have installed wakatime plugin in CLion and turn on the debug mode, but l cannot find .wakatime.log 
![1](https://user-images.githubusercontent.com/18008525/77924396-33738d00-72d6-11ea-9127-51162c372dd2.jpg)
![2](https://user-images.githubusercontent.com/18008525/77925014-efcd5300-72d6-11ea-9093-a874e6ced4ed.JPG)

**Comment by joechenrh** [comment]
can I manually download and install `wakatime-cli.zip` ?

**Comment by gandarez** [comment]
Does that need to keep opened @alanhamlett?

**Comment by alanhamlett** [comment]
Most likely this has been fixed by now.
