### ISSUE TITLE
feature [Coding time] bar  is not displayed in the lower right corner 

### ISSUE THREAD

**Issue by heicks** [wakatime/jetbrains-wakatime#150]
![image](https://user-images.githubusercontent.com/12287943/91968661-86e77c80-ed47-11ea-8006-7b84375f4783.png)
this is a https://wakatime.com/ site of vscode , 
-----

in jetbranis, not this feature? or err? idea ver: 2020.2
![image](https://user-images.githubusercontent.com/12287943/91968905-efcef480-ed47-11ea-9a6b-d7e745a77a63.png)

**Comment by luckydonald** [comment]
This is indeed missing: #107

**Comment by alanhamlett** [comment]
Added with v12.0.0.
