### ISSUE TITLE
WakaTime - Cannot run program, No such file or directory 

### ISSUE THREAD

**Issue by mohammadjavad948** [wakatime/jetbrains-wakatime#152]
i istalled wakatime plugin on webstorm but it doesnt track my works
after enabling debug mode i get this error
WakaTime - Cannot run program "/home/mohammad-javad/.wakatime/wakatime-cli/wakatime-cli": error=2, No such file or directory

im on ubuntu 20.04 - webstorm 2020.1

**Comment by stillfox-lee** [comment]
i got same issue, then i uninstall plugin and remove ${home}/.wakatime dir. Once I reinstalled the plugin, I was able to send the heartbeat successfully.

**Comment by gandarez** [comment]
Hi @mohammadjavad948 is this error still happening?

**Comment by mohammadjavad948** [comment]
Hi I managed to fix the issue by manually installing wakatime cli
