### ISSUE TITLE
[plugin] Your Unknown Editor plugin is malfunctioning

### ISSUE THREAD

**Issue by Berkmann18** [wakatime/jetbrains-wakatime#162]
I got the following email, I've got no idea why I'm getting this (I use VSCode, Vim, VS):
> Hey there,

> We noticed some unusual coding activity from your Unknown Editor WakaTime plugin Yesterday:
You have 24 hrs of coding activity.

> This is usually caused by another Unknown Editor extension tricking WakaTime into thinking you’re moving the cursor, or editing files.
If you would like to help fix this, **please add the list of Unknown Editor extensions you have installed** to an existing [GitHub issue](https://github.com/search?q=org%3Awakatime+%22unusual+coding+activity%22&type=issues) or just reply to this email.

**Comment by alanhamlett** [comment]
We were incorrectly including Google Calendar meetings in this check, but it's fixed now.

**Comment by Berkmann18** [comment]
Ah okay, good to know.

**Comment by adrianlzx1996** [comment]
I received the same error too.

May i know whether is this a false positive or i shall add a list of extensions installed in my editor for this?
