### ISSUE TITLE
Error in v12.0.1 UnsupportedClassVersionError

### ISSUE THREAD

**Issue by MuhammadZohair** [wakatime/jetbrains-wakatime#164]
![image](https://user-images.githubusercontent.com/26007909/112936364-21be0300-913f-11eb-97fe-3b58ca28775e.png)

Android/Device Details:
Android Studio 4.1.3
Build #AI-201.8743.12.41.7199119, built on March 11, 2021
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 3987M
Cores: 16

**Comment by vadrian89** [comment]
Same issue on Linux

Android Studio 4.1.3
Build #AI-201.8743.12.41.7199119, built on March 11, 2021
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.8.0-48-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 12
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: com.bloc.intellij_generator_plugin, com.herbert.george.flutter-snippets, com.thoughtworks.gauge, org.intellij.plugins.markdown, com.intellij.marketplace, org.jetbrains.kotlin, com.spidev.pubassist, Dart, io.flutter, de.mariushoefler.flutter_enhancement_suite, com.localizely.flutter-intl
Current Desktop: ubuntu:GNOME

**Comment by alanhamlett** [comment]
That was a bug in 12.0.0, but should have been fixed with 12.0.1?

**Comment by alanhamlett** [comment]
Should be fixed in v12.0.2?

**Comment by MuhammadZohair** [comment]
Fixed in v12.0.2!
