### ISSUE TITLE
The new update for IntelliJ IDEs is causing some slight hanging

### ISSUE THREAD

**Issue by CodeLover254** [wakatime/jetbrains-wakatime#166]
I just updated my Wakatime plugin in my set of Jetbrains IDEs and it causes the IDE to freeze for like a second or two as it updates the value on the new status bar icon you added for the plugin. Is there a way one can hide this icon from the status bar? Something like a setting? Otherwise, I believe there is a need for some optimization so that as it updates, there is no hanging.

**Comment by n19htz** [comment]
got the same issue

**Comment by viktor-poltorak** [comment]
Have the same issue
Wakatime version: 12.0.2

**Comment by alaegin** [comment]
The same one. 
I'm experiencing freezes approximately every minute or when calling some new windows to open.

Android Studio 4.1.3
Wakatime 12.0.2

**Comment by wkl007** [comment]
have the same issue,I have fallen back to version 11.0.1

**Comment by eloyekunle** [comment]
I am also experiencing this issue.

**Comment by Karetson** [comment]
the same problem here

**Comment by eloyekunle** [comment]
Disabling the status bar icon helps.

![Uploading 113186297...]

**Comment by TheAntimist** [comment]
@alanhamlett I still see this issue on v12,0.4 on IntelliJ IDEA 2020.3

**Comment by WilliamStam** [comment]
wow... ok. i narrowed it down to wakatime as well yesterday. but thought it was just me. pretty much wanted to throw my pc out the window. it felt like phpstorm was hanging constantly (micro hangs). i disabled wakatime and it seems to work ok. but by which time my outlook on the days productivity was very muddied. 

i really like the addition to the status bar tho. good job devs! but will probs have to disable it for now till the "stutters" are resolved. will keep trying. (im not seeing any wakatime issues in the idealogs tho so not sure how i can help. on save versions as TheAntimist above on windows

**Comment by CodeLover254** [comment]
I can also confirm that the update did not fix the issue.

**Comment by gooin** [comment]
I still have this issue on v12.0.4 on WebStorm 2020.3.1.

**Comment by jmbarbier** [comment]
The workaround from @viktor-poltorak works (disable status bar icon from context menu)

but the status bar was a gread addition

**Comment by alanhamlett** [comment]
Does v12.0.5 fix the issue for you?

**Comment by alanhamlett** [comment]
You can also now disable the status bar from WakaTime settings under your IDE's Tools menu.

**Comment by CodeLover254** [comment]
> Does v12.0.5 fix the issue for you?

So far no hanging. Thanks for the fix, Alan and Team.

**Comment by WilliamStam** [comment]
can also confirm. its perfect now!. thank you
