### ISSUE TITLE
Blocking UI when we focus again in jetbrain

### ISSUE THREAD

**Issue by roukmoute** [wakatime/jetbrains-wakatime#167]
I've downloaded your latest version (12.0.4) and [you have fixed](https://github.com/wakatime/jetbrains-wakatime/commit/33b8a38a491f4ca2874fa403120c4ddfead9d9ae) the problem with the PhpStorm 2020.3.3 to block UI.

But it still continue to blocking when we focus again in the IDE.  
I have the impression that this problem is due to one of the last updates that adds a graphical element in the IDE.

It works well in PhpStorm 2020.3.2.

[threadDumps-freeze-20210401-154934-PS-203.7717.64-Object.wait-6sec/threadDump-20210401-154934.txt](https://github.com/wakatime/jetbrains-wakatime/files/6243974/threadDump-20210401-154934.txt)

<details><summary>PhpStorm informations</summary>
<p>

```
PhpStorm 2020.3.3
Build #PS-203.7717.64, built on March 16, 2021
Runtime version: 11.0.10+8-b1145.96 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.80-2-manjaro
GC: ParNew, ConcurrentMarkSweep
Memory: 1917M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.settings.move.mouse.on.default.button=true
Non-Bundled Plugins: AceJump, Scratch, com.intellij.ideolog, com.wakatime.intellij.plugin, mobi.hsz.idea.gitignore, com.jetbrains.codeWithMe, name.kropp.intellij.makefile, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, me.mbolotov.cypress, ru.adelf.idea.dotenv
Current Desktop: i3
```

</p>
</details>

**Comment by alanhamlett** [comment]
Does v12.0.5 fix the issue for you?

**Comment by roukmoute** [comment]
It looks like perfect, thanks a lot.
