### ISSUE TITLE
status bar 显示的太长了  能否设置

### ISSUE THREAD

**Issue by dbeenlee** [wakatime/jetbrains-wakatime#168]
![image](https://user-images.githubusercontent.com/4352949/113374569-f7b74b80-939f-11eb-8148-59510b3dff8c.png)

如上图
只能选择显示或者不现实
能否增加设置显示的项目 用以缩短显示长度  比如：我只要看我coding时间  不要看browsing时间

**Comment by gandarez** [comment]
Hi,

Please post your question in English.

**Comment by alanhamlett** [comment]
Fixed with https://github.com/wakatime/wakatime-cli/pull/541. Add `status_bar_hide_categories = true` to your `~/.wakatime.cfg` file, then restart your IDE to get the fix.

**Comment by dbeenlee** [comment]
Thank you. It's hidden
