### ISSUE TITLE
Improve the status bar icon

### ISSUE THREAD

**Issue by mahozad** [wakatime/jetbrains-wakatime#173]
![IntelliJ screenshot](https://user-images.githubusercontent.com/29678011/117285356-c73e5380-ae1c-11eb-88d9-1330daee80f5.png)

The wakatime icon shown in IntelliJ status bar is not aesthetically pleasing:

- Its color does not match that of other [IDEA icons](https://github.com/JetBrains/intellij-community/tree/master/platform/icons/src)
- It is oversized
- The inner "w" shape is not legible

So, looking at [IntelliJ UI Guidelines](https://jetbrains.design/intellij/principles/icons/#action-icons) (and also [IntelliJ specifications of plugin logos](https://plugins.jetbrains.com/docs/intellij/plugin-icon-file.html)), I recreated the icon to fix the above problems.

Do you think these icons are good?
For dark UI: ![preview-dark](https://user-images.githubusercontent.com/29678011/117288297-349fb380-ae20-11eb-89b5-00ea479a7329.png)
For light UI: ![preview-light](https://user-images.githubusercontent.com/29678011/117288296-34071d00-ae20-11eb-9170-4fe2acb0ea7f.png)

[wakatime-new-svg-icons.zip](https://github.com/wakatime/jetbrains-wakatime/files/6433908/wakatime-new-svg-icons.zip)

**Comment by alanhamlett** [comment]
Fixed with 14cb2ced922e7143f63beafc4e2243c0a5d54239.

**Comment by alanhamlett** [comment]
Release just now in v13.0.2.
