### ISSUE TITLE
android studio freezing

### ISSUE THREAD

**Issue by Hosam11** [wakatime/jetbrains-wakatime#176]
I used android studio(4.2.1)  for flutter . I Move 2 package inside another package and android studio completely freezed for more than 3 minute until I had to close it with task manager. I tried to do same action again and it's repeated android studio freezed.

another time in the in bottom bar wakatime tell me "updating time" then freeze for 1 minute, so I'm now sure it's the reason for those behavior is the plugin

**Comment by nfacha** [comment]
Im having a similar problem with the same symptoms on phpstorm

**Comment by gandarez** [comment]
There's no "updating time" in the WakaTime plugin. Please do the following
1. Set `debug = true` into `~/.wakatime.cfg` file 
2. Clean up `~/.wakatime.log`
3. Restart the IDE
4. Do some activities
4. Attach log here

**Comment by alanhamlett** [comment]
Fixed in v13.1.0
