### ISSUE TITLE
Remove "Updating wakatime status bar" message

### ISSUE THREAD

**Issue by LoneDev6** [wakatime/jetbrains-wakatime#177]
Hello,
is it possible to hide this message? It's a bit annoying to see it popup every time I switch file.
![immagine](https://user-images.githubusercontent.com/27242001/120356369-914d9b80-c304-11eb-918d-8fc36c64d128.png)

Thanks!

**Comment by alanhamlett** [comment]
You can disable the status bar in from the WakaTime Settings menu. That should stop that popup.

**Comment by LoneDev6** [comment]
Amazing, thanks a lot!
