### ISSUE TITLE
wakatime have problem with android studio

### ISSUE THREAD

**Issue by mohkhz2001** [wakatime/jetbrains-wakatime#178]
I use ubuntu and when I wakatime on android studio, shows nothing.
and I added the API key manually and still doesn't work.

**Comment by gandarez** [comment]
Hi @mohkhz2001,

Please do the following
1. Set `debug = true` into `~/.wakatime.cfg` file 
2. Clean up `~/.wakatime.log`
3. Restart the IDE
4. Do some activities
4. Attach log here

**Comment by mohkhz2001** [comment]
@gandarez 
thank you but it was solved automaticly.
