### ISSUE TITLE
Wakatime doesn't count time spend in console(terminal)

### ISSUE THREAD

**Issue by Mausino** [wakatime/jetbrains-wakatime#181]
Hi, i spend almost 6 hrs on PhpStorm but it counted me like 1h 34m

it is not first time when i looked my time and was poorly.

The main reason i know now is, when i must do lot of my work do in console/terminal... like create entities, relationships, migrating, debug routes and others...  the time is not counting...

Also will nice if will possible has in **dashboard time spend on console/terminal**... because it is some time if you configure all stuff from yarn, node, containers etc... takes loots of time but time it looks as i am not working... 

Hope, that will somebody confirm the same issue on jetbrains IDE.  (sorry for English)

**Comment by gandarez** [comment]
Hi @Mausino,

You might install WakaTime for terminal also. Please refer to https://wakatime.com/terminal.

**Comment by Mausino** [comment]
@gandarez thank you for your answer

But i am using terminal inside PhpStorm...  There is WakaTime install as plugin, and should count it by PhpStorm plugin

I understand the idea of WakaTime separately for terminal..

**Comment by gandarez** [comment]
The terminal inside any IDE is an extension from your computer's terminal so to get it working you might install terminal plugins.

**Comment by Mausino** [comment]
@gandarez thanks i didn't know this :+1:  in installed it :) will see
