### ISSUE TITLE
Set proxy via jvm property is not recommended

### ISSUE THREAD

**Issue by Xuanwo** [wakatime/jetbrains-wakatime#182]
If the proxy is set via wakatime, IDEA will warning likes following:

![image](https://user-images.githubusercontent.com/5351546/127623449-f3cede98-a317-40f3-8d88-cba1241ca844.png)

I believe the warning is related to:

https://github.com/wakatime/jetbrains-wakatime/blob/1fbc1b8fa4b2b509b308c659a743f726c2a83ab0/src/com/wakatime/intellij/plugin/Dependencies.java#L359-L360

Maybe we can use the proxy setting provided by IDEA instead?

**Comment by alanhamlett** [comment]
Yes, that would be better. We just need to make sure IDEA's proxy setting is used by JVM when making http(s) requests. If not, we could use the IDEA proxy setting for storing the proxy values and just temporarily set the system JVM proxy when making requests and then un-set it after the request is completed.

**Comment by Xuanwo** [comment]
> If not, we could use the IDEA proxy setting for storing the proxy values and just temporarily set the system JVM proxy when making requests and then un-set it after the request is completed.

I'm not particularly familiar with IDEA plugin development and I have these questions.

1. Will the requests sent by the plugin also be used when the IDEA proxy has been configured?
1. if not, does the plugin have an API to get the proxy already configured by IDEA?

temporarily set the system JVM proxy for every request doesn't look so nice to me.

**Comment by alanhamlett** [comment]
Fixed in fa12d4ce0c922057f644253279a8701139385808 and released in v14.0.1.
