### ISSUE TITLE
IntelliJ Idea: updating wakatime status bar very often

### ISSUE THREAD

**Issue by jirikrepl** [wakatime/jetbrains-wakatime#184]
I started using wakatime 4 days ago. It worked well, but now in the status bar, it shows loading with "updating wakatime status bar" every 15 minutes.

<img width="449" alt="Screen Shot 2021-08-26 at 17 33 30" src="https://user-images.githubusercontent.com/2588479/130992403-a3901c29-4173-4e8b-bacc-a77f4b823835.png">

After I enabled debug in settings, it showed 502 error
<img width="186" alt="Screen Shot 2021-08-26 at 17 34 34" src="https://user-images.githubusercontent.com/2588479/130992628-5ad9bffa-2bc8-4261-8aab-dea02c76230d.png">

**Comment by jirikrepl** [comment]
@alanhamlett Hello, thank you. Today I saw this in the status bar:


<img width="615" alt="Screen Shot 2021-08-30 at 16 23 12" src="https://user-images.githubusercontent.com/2588479/131354522-05374223-e2c6-4899-89d7-fe4cb0bf9f79.png">

and then it changed to:

<img width="116" alt="Screen Shot 2021-08-30 at 16 24 29" src="https://user-images.githubusercontent.com/2588479/131354691-072b883f-8f1e-479f-b1a1-77a3515b2e3d.png">

**Comment by alanhamlett** [comment]
Yes, it's related to [API issues](https://status.wakatime.com/) again. Once our API scales up to handle the load it will be working again.

**Comment by jirikrepl** [comment]
ok, no worries. But even when your API works fine I find it quite distracting to often see progress bar updating.
Seems to be like every half hour or when the IDE window gets focus.
Maybe it would be better to not show a progress bar at all, and just sync silently.

**Comment by alanhamlett** [comment]
> Maybe it would be better to not show a progress bar at all, and just sync silently.

 Yes, we need to fetch the code stats first then update the status bar (which automatically shows a progress bar) so it's instantaneous.

**Comment by jirikrepl** [comment]
ok:)

**Comment by alanhamlett** [comment]
Fixed in v13.1.0.
