### ISSUE TITLE
not appear any windows to input api key after install on Android studio Arctic fox 2020

### ISSUE THREAD

**Issue by Theonlysmartboy** [wakatime/jetbrains-wakatime#185]
After following the steps to install the plugin on android studio and restating the IDE, I am not presented by a window or field to enter my API key. I have so far done this on android studio mac without success

**Comment by Theonlysmartboy** [comment]
Yes I do but it does not show the area to enter the api key

**Comment by alanhamlett** [comment]
I just tested with Android Studio Arctic Fox on Mac and for me the `WakaTime Settings` menu opens a dialog popup with a field `API Key`. Can you send a screenshot of what you're seeing?

**Comment by alanhamlett** [comment]
Also maybe there's a hint to why it's not showing in your `idea.log` file, which can be found from `Help -> Show Log in Finder`.

**Comment by Theonlysmartboy** [comment]
I do have the ```Wakatime Settings``` menu and I have also noticed that it is collecting and sending stats just after installation even though I was unable to enter the ```API Key```

**Comment by alanhamlett** [comment]
That means the api key must have been previously entered when installing a WakaTime plugin in the past. That's normal, it won't prompt if the api key is already present in the config file.
