### ISSUE TITLE
SSLException

### ISSUE THREAD

**Issue by gilbarbara** [wakatime/jetbrains-wakatime#19]
Hey,
I'm getting this error in PHPStorm 8.0.2 using WakaTime plugin 4.0.1:
`java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`

**Comment by alanhamlett** [comment]
Yea, your JDK needs cacerts to verify the SSL connection to wakatime.com. Does using a different JDK fix the issue for you?

**Comment by gilbarbara** [comment]
It's fixed already

[s]
