### ISSUE TITLE
Scala Worksheet recorded as SuperColider

### ISSUE THREAD

**Issue by peteanning** [wakatime/jetbrains-wakatime#190]
Despite setting a custom Rule to map *.sc to Scala and Language SuperColider to Scala all my Scala worksheets are being recorded against this language. Whilst I am sure SuperColider is very cool for some people it is really frustrating I can see my time allocated to it. Won't buy a subscription until I can fix this issue.
<img width="707" alt="Screenshot 2021-10-18 at 11 51 20" src="https://user-images.githubusercontent.com/22272449/137717558-0fe80092-313c-4470-984e-3451365d8eef.png">

**Comment by alanhamlett** [comment]
That's due to the second rule using `equals` when it should be changed to `ends with`, to match files ending in `.sc`.
