### ISSUE TITLE
Tracking Remote Editing

### ISSUE THREAD

**Issue by bastianleicht** [wakatime/jetbrains-wakatime#193]
Hi, is there a way to track remote Editing? (Editing on a RemoteHost)

**Comment by alanhamlett** [comment]
I'll need more details... 

* editing a project/file via remote file system?
* using the IDE via VNC/RDP on a remote desktop?
* using another extension that enables editing remote projects?

**Comment by bastianleicht** [comment]
Sorry, I meant Editing over the remote file system. If it's posible.

**Comment by alanhamlett** [comment]
Related to wakatime/wakatime-cli#623, which added support for `ssh://` and `sftp://` remote files.

**Comment by alanhamlett** [comment]
The recent release is working for you, and you can edit remote files now?

**Comment by bastianleicht** [comment]
Yes it worked perfectly :^)
