### ISSUE TITLE
Not Showing logs from wakatime

### ISSUE THREAD

**Issue by Kayuemkhan** [wakatime/jetbrains-wakatime#197]
I've upgraded android studio version to 203.*** and my wakatime is not working and it's not sending the time and also not showing the time in the bottom like as past .

**Comment by alanhamlett** [comment]
If you re-install the plugin does it work?

**Comment by Kayuemkhan** [comment]
No ! After reinstall it wasn't working. 
What I did is: Just delete log file and make debug option true and also restarted the IDE ! It works fine.

**Comment by alanhamlett** [comment]
You should turn off debug mode now that it's working, or the plugin will make your IDE slow.
