### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [wakatime/jetbrains-wakatime#199]
Hey there!

I belong to an open source security research community, and a member (@ready-research) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by alanhamlett** [comment]
https://wakatime.com/security.txt

**Comment by JamieSlome** [comment]
@alanhamlett - we have sent an e-mail to you, but just for reference, you can also view the report here:

https://huntr.dev/bounties/92511e52-6607-4d4d-a15d-606b21197eb5/

It is private and only accessible to maintainers with repository write permissions. Let me know if you have any questions!

**Comment by alanhamlett** [comment]
That means you didn't even read our security doc. Please don't create spam issues on GitHub.
