### ISSUE TITLE
phpStorm hangs on startup after installing WakaTime

### ISSUE THREAD

**Issue by krzksz** [wakatime/jetbrains-wakatime#20]
Hi!
I am experiencing problem with phpStorm getting completely unresponsive after installing WakaTime on start-up. I tried running it as admin as well as deleting `.WebIde80` folder and reinstalling plugin.

You can check logs here: https://www.dropbox.com/s/auypbq92ttpoq0n/phpStorm-logs.rar?dl=0

**Comment by alanhamlett** [comment]
Hi @krzksz,

Can you try the latest version of the plugin, v4.0.3? This fix could have been the problem:
7bd0a138c0979fb343cad9daeaf30242b930b081

**Comment by krzksz** [comment]
Thank you for your response @alanhamlett!

Well, that didn't solve the problem directly(phpStorm still hangs on startup), but it made me realise how dumb I am and install Python, which helped. Everything is now working fine :smile:
