### ISSUE TITLE
WakaTime is stuck on inititialized and doesn't display time

### ISSUE THREAD

**Issue by pavloko** [wakatime/jetbrains-wakatime#208]
WakaTime plugin for PyCharm with version 13.1.14 doesn't display logged time until you click on it.

![Screenshot 2022-04-14 at 14 51 24](https://user-images.githubusercontent.com/12280422/163385505-5da50994-1868-4b94-b2fc-dbd480324158.png)

This hasn't happened in the previous version.

**Comment by moonD4rk** [comment]
Some Problem, here's my Goland info
```
GoLand 2022.1
Build #GO-221.5080.224, built on April 14, 2022
Licensed to HackBrowserData / moonD4rk
Subscription is active until October 11, 2022.
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Registry:
    suggest.all.run.configurations.from.context=true
    ide.completion.variant.limit=500
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    ……
    com.wakatime.intellij.plugin (13.1.14)

```
I already reinstalled `wakatime` plugin and restart `Goland`, always show `initialized`.

**Comment by moonD4rk** [comment]
Hi, I found it's network problem for me, I could not find `api.wakatime.com` IP with default DNS server. try resolve it with add 
this line in `/etc/hosts`

```
# /etc/hosts
143.244.210.202 api.wakatime.com

```

**Comment by alanhamlett** [comment]
@pavloko is yours not updating also networking related?

**Comment by pavloko** [comment]
I'm not sure what @moonD4rk means he couldn't find the IP. If I `ping api.wakatime.com` from the console, I can see 143.244.210.202 IP resolved in the response.

**Comment by pavloko** [comment]
Yes, I can see logs like `WakaTime - Executing CLI:....`. 

I can't understand what's happening, but now the time indicator is missing completely:

![Screenshot 2022-04-21 at 18 09 32](https://user-images.githubusercontent.com/12280422/164489063-c21e3f47-a778-4f7a-8e7a-12ba904cb7a6.png)

**Comment by YOLOabrcdbr** [comment]
> Hi, I found it's network problem for me, I could not find `api.wakatime.com` IP with default DNS server. try resolve it with add this line in `/etc/hosts`
> 
> ```
> # /etc/hosts
> 143.244.210.202 api.wakatime.com
> ```

It totally worked!

**Comment by pavloko** [comment]
I apologize for the late response, but the problem just went away for me after reinstalling the plugin a few times.
