### ISSUE TITLE
`hide_project_folder` ignored

### ISSUE THREAD

**Issue by nix6839** [wakatime/jetbrains-wakatime#209]
OS: Windows 10
IDE: Android Studio Chipmunk | 2021.2.1
WakaTime CLI version: v1.45.1
WakaTime Extension version: Latest(13.1.14) on <https://plugins.jetbrains.com/plugin/7425-wakatime/versions>
My `.wakatime.cfg`:

```ini
[settings]
hide_project_folder = true
exclude = .*
include = \
/programming/study/
api_key = ***
proxy = 
debug = true
status_bar_enabled = true
```

When I working on `C:\Users\${user}\programming\study\learn_flutter`, the full directory path is sent.
Maybe change below line to: `cmds.add("--alternate-project");` and publish new version of extension to store.
https://github.com/wakatime/jetbrains-wakatime/blob/afbeaf4cd1066a18c6787ca122bf80be2c1a663d/src/com/wakatime/intellij/plugin/WakaTime.java#L407

Thank you for your hard work.

**Comment by gandarez** [comment]
Hi @nix6839,

Are you under any rev control like git, svn, ...? Could you please enable `debug = true` in your `.wakatime.cfg`, modify/save any file in this folder and attach here the logs?

**Comment by nix6839** [comment]
Oh... It was solved by using git. thank you!!!

**Comment by alanhamlett** [comment]
Also using `--alternate-project` with a7533fdf2ff11f15b1d755ba32bfb046a08c9bbb, that way when using multiple IDEs they should all detect the same project name and only fallback to the Jetbrains' project when one can't be auto-detected.
