### ISSUE TITLE
No API-key window after restart

### ISSUE THREAD

**Issue by kolletzki** [wakatime/jetbrains-wakatime#21]
I just installed the WakaTime plugin for WebStorm, and I didn't get any window to enter my API-key.
I already reinstalled the plugin, and restarted WebStorm several times, but no window appeared to enter my API-key.

I'm using WebStorm 9.0.3 with WakaTime 4.0.3.

**Comment by alanhamlett** [comment]
Do you have a `.wakatime.cfg` file in your home directory? The plugins share a common config file and it won't prompt for your api key if it's already in that file.

**Comment by alanhamlett** [comment]
This should be fixed in v4.0.6 of the plugin.
