### ISSUE TITLE
Backoff delay broken

### ISSUE THREAD

**Issue by sanasol** [wakatime/jetbrains-wakatime#210]
Somehow got many errors, so plugin started "backoff algorithm"
But delay time calculation based on tries counter is went crazy. 
So I have to reset it manually to make it work without waiting until June 🤣

>{"caller":"pkg/backoff/backoff.go:40","func":"backoff.WithBackoff","level":"debug","message":"execute heartbeat backoff algorithm","now":"2022-05-13T21:24:57+03:00","version":"v1.45.2"}
>{"caller":"pkg/backoff/backoff.go:78","func":"backoff.shouldBackoff","level":"debug","message":"exponential backoff tried 16 times since May 13 20:32:37, will **retry at May 25 05:36:37**","now":"2022-05-13T21:24:57+03:00","version":"v1.45.2"}

>{"caller":"pkg/backoff/backoff.go:40","func":"backoff.WithBackoff","level":"debug","message":"execute heartbeat backoff algorithm","now":"2022-05-13T22:18:06+03:00","version":"v1.45.2"}
>{"caller":"pkg/backoff/backoff.go:78","func":"backoff.shouldBackoff","level":"debug","message":"exponential backoff tried 17 times since May 13 21:32:58, will **retry at Jun  5 15:40:58**","now":"2022-05-13T22:18:06+03:00","version":"v1.45.2"}

**Comment by sanasol** [comment]
probably hould not be so much _exponential_ 😄

**Comment by gandarez** [comment]
Backoff never gets longer than `1h` but it incorrectly logs the next tick. I fixed it in this [PR](https://github.com/wakatime/wakatime-cli/pull/730) which is pending for review.

**Comment by alanhamlett** [comment]
Restart your IDE to get the fix.
