### ISSUE TITLE
Install older version of Wakatime PhpStorm Plugin

### ISSUE THREAD

**Issue by bmenekl** [wakatime/jetbrains-wakatime#226]
Hello everybody.

I have been happily using wakatime for some time now, until 2 months ago (around May 2022 I think) my plugin lost all connectivity. After some investigation I found out that the latest version (14.0.6) which uses wakatime-cli v. 1.38.0 (which requires golang 1.18 to work) is not compatible with my (admittedly old) os version (Mac Os 10.12.6 Sierra). Mainly due to my OS not supporting go version 1.18.

The last versions that were usable in my machine were wakatime version 13.1.14 and wakatime-cli version 1.38.0

I tried installing the 1.38.0 version of wakatime-cli manually, but it did not work.

So now I am wondering if (and how) I could install an older version of wakatime PhpStorm plugin. The 13.1.14 version that was working well in my machine.

Thanks in advance.

**Comment by alanhamlett** [comment]
Related to the parent issue https://github.com/wakatime/wakatime-cli/issues/732.

**Comment by alanhamlett** [comment]
> I could install an older version of wakatime PhpStorm plugin.

You can open your IDE, [download this older release](https://github.com/wakatime/wakatime-cli/releases/download/v1.39.1-alpha.1/wakatime-cli-darwin-amd64.zip), unzip it to `~/.wakatime/` so it replaces `~/.wakatime/wakatime-cli-darwin-amd64`, then use your IDE without restarting it. If you restart your IDE, it will auto-update to the latest wakatime-cli release which uses Go 1.18.

**Comment by bmenekl** [comment]
Worked perfectly. I was doing the same apart from NOT restarting :) Apparently makes all the difference.

Million thanks.
