### ISSUE TITLE
Can't enter api key

### ISSUE THREAD

**Issue by jsyang-dev** [wakatime/jetbrains-wakatime#227]
I installed the plugin and re-launched the IDE, but the window asking me to enter the api key doesn't pop up.
Reinstalling the plugin doesn't solve the problem.

**Comment by Blorgen** [comment]
There are wakatime settings in Tools, enter the api key there

**Comment by notflask** [comment]
> There are wakatime settings in Tools, enter the api key there

wakatime settings also dont appear in tools

![image](https://user-images.githubusercontent.com/78703851/179178395-48c76520-063e-4823-8f85-4a2bfd195910.png)

**Comment by Blorgen** [comment]
> > There are wakatime settings in Tools, enter the api key there
> 
> wakatime settings also dont appear in tools

not in File > settings > tools, just Tools
![image](https://user-images.githubusercontent.com/39773024/179220780-adc807fa-0518-4856-b83a-88bb2473aa74.png)

**Comment by notflask** [comment]
> > > There are wakatime settings in Tools, enter the api key there
> > 
> > 
> > wakatime settings also dont appear in tools
> 
> not in File > settings > tools, just Tools ![image](https://user-images.githubusercontent.com/39773024/179220780-adc807fa-0518-4856-b83a-88bb2473aa74.png)

it doesn't appear in tools or file > settings > tools
but i restarted my idea two times and it started working xd

**Comment by jsyang-dev** [comment]
I found it in the Tools menu. Thank you.
