### ISSUE TITLE
Android studio didnt ask for api key

### ISSUE THREAD

**Issue by Kamil-Malik** [wakatime/jetbrains-wakatime#229]
After installing wakatime based on guide, i restart my Android Studio. but it didnt ask me for any api key, even when i try to reinstall the android studio itself

**Comment by alanhamlett** [comment]
You're using plugin version 14.1.0?

**Comment by Kamil-Malik** [comment]
14.0.6 sir

**Comment by alanhamlett** [comment]
That was fixed in v14.1.0 released today. Please upgrade and it will prompt for your api key.
