### ISSUE TITLE
Wakatime dashboard not reporting plugin status

### ISSUE THREAD

**Issue by nicholaspshaw** [wakatime/jetbrains-wakatime#230]
Appears to be installed correctly in RubyMine as it's available in tools menu.

Contains API key, have got debug mode on.  I do not see any real areas, however wakatime dashboard shows nothing for me but a spinner.

Can you suggest what might be going on here?

wakatime log highlights:

`
{"caller":"pkg/deps/deps.go:65","func":"deps.WithDetection","level":"warning","message":"error parsing language of string \"Cucumber\"","now":"2022-08-08T12:09:39+01:00","version":"v1.53.4"}
{"caller":"pkg/ini/ini.go:98","func":"ini.(*WriterConfig)","level":"debug","message":"failed to acquire mutex: timeout acquiring mutex","now":"2022-08-08T12:04:14+01:00","version":"v1.53.4"}
{"caller":"pkg/api/heartbeat.go:27","func":"api.(*Client)","level":"debug","message":"sending 2 heartbeat(s) to api at https://api.wakatime.com/api/v1/users/current/heartbeats.bulk","now":"2022-08-08T12:09:39+01:00","version":"v1.53.4"}
{"caller":"pkg/api/heartbeat.go:52","func":"api.(*Client)","level":"debug","message":"heartbeats: [{\"branch\":\"master\",\"category\":\"coding\",\"cursorpos\":null,\"dependencies\":null,\"entity\":\"/Users/nicholasshaw/Projects/xyz.feature\",\"type\":\"file\",\"is_write\":null,\"language\":\"Gherkin\",\"lineno\":null,\"lines\":80,\"project\":\"xyz\",\"time\":1659956969.533,\"user_agent\":\"wakatime/v1.53.4 (darwin-21.6.0-arm64) go1.18.4 Ruby/2022.1.3 Ruby-wakatime/14.1.0\"},{\"branch\":\"master\",\"category\":\"coding\",\"cursorpos\":29,\"dependencies\":null,\"entity\":\"/Users/nicholasshaw/Projects/xyz.feature\",\"type\":\"file\",\"is_write\":true,\"language\":\"Cucumber\",\"lineno\":11,\"lines\":80,\"project\":\"xyz\",\"time\":1659956974.153,\"user_agent\":\"wakatime/v1.53.4 (darwin-21.6.0-arm64) go1.18.4 Ruby/2022.1.3 Ruby-wakatime/14.1.0\"}]","now":"2022-08-08T12:09:39+01:00","version":"v1.53.4"}
{"caller":"cmd/heartbeat/heartbeat.go:75","func":"heartbeat.Run","level":"debug","message":"successfully sent heartbeat(s)","now":"2022-08-08T12:09:40+01:00","version":"v1.53.4"}
{"caller":"pkg/offline/offline.go:106","func":"offline.WithSync","level":"debug","message":"execute offline sync with file /Users/nicholasshaw/.wakatime.bdb","now":"2022-08-08T12:09:40+01:00","version":"v1.53.4"}
{"caller":"pkg/offline/offline.go:146","func":"offline.Sync","level":"debug","message":"no queued heartbeats ready for sending","now":"2022-08-08T12:09:40+01:00","version":"v1.53.4"}
{"caller":"cmd/offlinesync/offlinesync.go:48","func":"offlinesync.Run","level":"debug","message":"successfully synced offline activity","now":"2022-08-08T12:09:40+01:00","version":"v1.53.4"}
`

**Comment by alanhamlett** [comment]
Should be fixed now? This was a backend data processing delay on our end.

**Comment by nicholaspshaw** [comment]
yup I can see some statistics in there now, thank you for taking a look!
