### ISSUE TITLE
Wakatime is wrongly mixing different projects with same folder name

### ISSUE THREAD

**Issue by inDeev** [wakatime/jetbrains-wakatime#231]
In structure e.g.
```
... / projects / project1 / backend  (in PHPStorm aliased as BE_P1)
                          / frontend (in PHPStorm aliased as FE_P1)
               / project2 / backend  (in PHPStorm aliased as BE_P2)
                          / frontend (in PHPStorm aliased as FE_P2)
```
are all backends / frontends processed as one project. Although each have own renamed alias in PHPStorm.

**Comment by alanhamlett** [comment]
The plugin uses first the Git repo folder as the project name, the second the PHPStorm project if a Git folder isn't found. To overwrite that, use a [project map](https://wakatime.com/faq#create-projects) in your `~/.wakatime.cfg` which works based on the file path similar to your aliased projects in PHPStorm.

The reason we use Git first is to support PHPStorm with other editors on the same machine, that way all wakatime plugins use the same project names and you don't end up with the same project having two different names on your dashboard.

**Comment by Rapid0s** [comment]
I have the same problem all my projects are recorded as www since this is my project root.
