### ISSUE TITLE
 Webstorm2022.2.2  no pop-up

### ISSUE THREAD

**Issue by detykoruqeho6** [wakatime/jetbrains-wakatime#233]
What should I do if there is no pop-up window for me to enter the key after the Webstorm2022.2.2 Installation and restart

**Comment by alanhamlett** [comment]
Do you have a Tools -> WakaTime Settings menu?

**Comment by detykoruqeho6** [comment]
I looked closely and couldn't find this menu item.

**Comment by alanhamlett** [comment]
Try re-installing the plugin then check your `idea.log` file to see why it's not loading the plugin.

**Comment by detykoruqeho6** [comment]
2022-10-06 11:09:16,968 [    205]   WARN - #c.i.i.p.PluginManager - <resource-bundle>com.jetbrains.webstorm.WebstormCommon</resource-bundle> tag is found in an xml descriptor included into the platform part of the IDE but the platform part uses predefined bundles (e.g. ActionsBundle for actions) anyway; this tag must be replaced by a corresponding attribute in some inner tags (e.g. by 'resource-bundle' attribute in 'actions' tag)

2022-10-06 11:09:17,113 [    350]   INFO - #c.i.i.p.PluginManager - Module intellij.grazie.properties is not enabled because dependency com.intellij.properties is not available
Module intellij.grazie.java is not enabled because dependency com.intellij.java is not available
Module intellij.space.php is not enabled because dependency com.jetbrains.php is not available
Module intellij.space.java is not enabled because dependency com.intellij.java is not available
Module intellij.space.kotlin.scripting is not enabled because dependency org.jetbrains.kotlin is not available
Module intellij.webDeployment/phpStorm is not enabled because dependency com.intellij.modules.phpstorm is not available
Module intellij.restClient/microservicesUI is not enabled because dependency com.intellij.microservices.ui is not available
Module intellij.diagram.properties is not enabled because dependency com.intellij.properties is not available
Module intellij.diagram.java is not enabled because dependency com.intellij.java is not available
Module intellij.space.kotlin is not enabled because dependency intellij.space.kotlin.scripting is not available
Module intellij.javascript.debugger.javaee is not enabled because dependency com.intellij.javaee is not available
Module intellij.javascript.debugger.nashorn is not enabled because dependency com.intellij.java is not available
Module intellij.javascript.devkit is not enabled because dependency intellij.devkit.core is not available
Module intellij.clouds.docker.java is not enabled because dependency com.intellij.java is not available

**Comment by detykoruqeho6** [comment]
No other error messages were found

**Comment by diorcula** [comment]
for IntelliJ, i have the same issue;
no popup, but also no option in the menu's to enter the API key manually?

**Comment by alanhamlett** [comment]
No WakaTime menu under the Tools menu means WakaTime isn't installed or not loading in IntelliJ. If IntelliJ shows the plugin as installed, then there should be an error message in your `idea.log` file indicating why WakaTime wasn't loaded or crashed before adding it's menu item.

Here's how to find your `idea.log` file:
https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by alanhamlett** [comment]
Without an error message from your `idea.log` we can't debug this. Closing for now.
