### ISSUE TITLE
Jetbrains Wakatime not posting stats

### ISSUE THREAD

**Issue by david-kariuki** [wakatime/jetbrains-wakatime#240]
Hi there, I am using Intellij Ultimate on Fedora Linux 37. This issue was also persistent on 36.
I have wakatime integration on my chrome too. 
My problem is, the wakatime on my Intellij IDE does not post stats to my wakatime profile. I only see stats from my chrome browser. It has been this way for the last 2 months. On VSCode, the experience is much better, I see my stats on the dashboard, unlike Intellij.
Do you have such an issue on your tracker?

**Comment by alanhamlett** [comment]
Haven't seen this before. Please look for WakaTime related logs in your `idea.log` file so we can figure out what's going wrong:

https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by nuth-vireak** [comment]
```
2022-12-13 01:28:44,639 [ 105432]   INFO - #c.i.i.p.DynamicPlugins - Plugin com.wakatime.intellij.plugin is not unload-safe because it declares components
```

I also have the same issue in Inteliij

**Comment by david-kariuki** [comment]
How do I send/attach these logs privately?

**Comment by alanhamlett** [comment]
@david-kariuki you can send the logs to `support@wakatime.com`

@nuth-vireak please create an issue on the github profile readme's repo since we don't maintain those.

**Comment by david-kariuki** [comment]
Alright. I have sent a zip

**Comment by alanhamlett** [comment]
Got the logs. I'm seeing `WakaTime - Command finished with return value: 102` which means there was a networking error when trying to sync with the api. Can you check your `~/.wakatime.log` file for errors?

**Comment by david-kariuki** [comment]
VS code works perfectly

**Comment by alanhamlett** [comment]
Can you email your `~/.wakatime.log` file?

**Comment by david-kariuki** [comment]
Hi, @alanhamlett , I have mailed you the `wakatime.log` and `.cfg` files

**Comment by alanhamlett** [comment]
I see the problem, you have the example (invalid) proxy defined in your `~/.wakatime.cfg` file. You should delete all those example lines and only leave two lines in that cfg file:
```ini
[settings]
api_key = XXXX
```
Replacing `XXXX` with your real secret api key.

**Comment by alanhamlett** [comment]
Normally you shouldn't need to edit `~/.wakatime.cfg` manually unless you want to add advanced configs. Your IDE would create that cfg file the first time you install the wakatime plugin.

**Comment by david-kariuki** [comment]
Thank you @alanhamlett 
This worked for me. Great work.
