### ISSUE TITLE
The input box for entering the API key does not pop up.

### ISSUE THREAD

**Issue by suyanhanx** [wakatime/jetbrains-wakatime#242]
Just installed the plugin on WebStorm 2022.3.1, and the input box for entering the API key does not pop up.
So I can't start my session.

Wouldn't you consider moving the place where you fill in the API key directly into the preferences?

**Comment by Eeveelution** [comment]
Same here with rider 2022.3

**Comment by alanhamlett** [comment]
The api key menu is located at `Tools → WakaTime Settings`.

**Comment by suyanhanx** [comment]
> The api key menu is located at `Tools → WakaTime Settings`.
> 
> When you open the menu from there, does it already have an api key or is it empty?

No. I cannot find this menu. 
![image](https://user-images.githubusercontent.com/24221472/211276286-6f3ef2fc-d06b-4d91-8a06-d3479c05f924.png)

**Comment by suyanhanx** [comment]
Thanks. I found it!

**Comment by alanhamlett** [comment]
Was there already an api key set? That's normally why it doesn't prompt to enter one when installing it, since all the plugins share the same config file if you've installed another WakaTime plugin previously, it won't prompt.

**Comment by suyanhanx** [comment]
> Was there already an api key set? That's normally why it doesn't prompt to enter one when installing it, since all the plugins share the same config file if you've installed another WakaTime plugin previously, it won't prompt.

Yes, there is already an API key set. Thanks for your help.

It seems that the API key changed a few months ago, and I received an email reminder that it had not been used for a long time, so I thought I would look for a place to update the key.

**Comment by alanhamlett** [comment]
Glad it's working now 👍
