### ISSUE TITLE
No coding record

### ISSUE THREAD

**Issue by wwt0805** [wakatime/jetbrains-wakatime#245]
Dear all. 
When I install the wakatime plugin there is a problem I encouter.
![waka1](https://user-images.githubusercontent.com/58569651/221746158-1d12f4c3-425c-453b-a238-ef537ad00c97.png)
It runs correctly in Chrome and Office but it doesn't work in Pycharm，Idea and sublime。
The wakatime bar can be seen in the bottom of the IDE page while it doesn't record any coding time and type. 
![waka2](https://user-images.githubusercontent.com/58569651/221746895-ea0bc4af-9b4d-48d9-8633-a0487a7a3391.png)
There's no any information about coding in wakatime dashboard.
Can any help me to solve this fatal problem?
Thank you!

**Comment by alanhamlett** [comment]
Let's start with Sublime. First, turn on debug mode. Next, open your Sublime Console window:
https://github.com/wakatime/sublime-wakatime#troubleshooting

Then type in a file and copy/paste any logs you see here.

**Comment by wwt0805** [comment]
> Let's start with Sublime. First, turn on debug mode. Next, open your Sublime Console window: https://github.com/wakatime/sublime-wakatime#troubleshooting
> 
> Then type in a file and copy/paste any logs you see here.

THX，I've tried in sublime console. It exited with status code:  1
![waka3](https://user-images.githubusercontent.com/58569651/221773279-dc3d595f-198c-4224-a5da-7902e464ea91.png)
I don't know where to find the meaning of  status code. 
Can you help me to explain it? Thanks again.

**Comment by alanhamlett** [comment]
That should be in your `~/.wakatime.log` file.

**Comment by wwt0805** [comment]
> That should be in your `~/.wakatime.log` file.
I've checked the log file. it  shows as following:
![waka4](https://user-images.githubusercontent.com/58569651/222021358-e70455b9-2a8b-440f-921c-b418811c4e38.png)
Are there network problems in my computer? I'm not sure

**Comment by alanhamlett** [comment]
Are there any other errors in there because that error is for the status bar updating not uploading code stats. It's probably the same error though, if it's not able to connect. Do you have a proxy configured?

**Comment by wwt0805** [comment]
> Are there any other errors in there because that error is for the status bar updating not uploading code stats. It's probably the same error though, if it's not able to connect. Do you have a proxy configured?

I've found the point you mentioned. 
It's indeed need to set the proxy params.
I attempted saveral times by many ways. Fortunately, it's done!
Thank you for your help ^_^
