### ISSUE TITLE
No synchronization after changing hostname on fedora

### ISSUE THREAD

**Issue by david-kariuki** [wakatime/jetbrains-wakatime#246]
My wakatime stopped synchronization after changing my hostname from `fedora` to `Fedora`.

Below is my configuration

    [settings]
    api_key = waka_********************************
    proxy = 
    debug = false
    status_bar_enabled = true

    hide_file_names = true
    hide_project_names = true
    hide_branch_names = true
    hide_project_folder = true

**Comment by alanhamlett** [comment]
After turning on debug mode, are there any errors in your `~/.wakatime.log` file?

**Comment by david-kariuki** [comment]
I've noticed an invalid API KEY error message. Does the API KEY expire?

**Comment by david-kariuki** [comment]
It's working well now. Maybe I added some character while tweaking the `cfg`. Its working well now, thank you
