### ISSUE TITLE
Track active tasks

### ISSUE THREAD

**Issue by PsychodelEKS** [wakatime/jetbrains-wakatime#26]
Currently, only active project is tracked, it would be nice, if it was possible to track active task also for extended stats (divided by project+task).

Some more feature requests:
 - manual start/stop, cause working on the task does not mean only typing code, with hotkeys and sound notifications

**Comment by alanhamlett** [comment]
I think tracking tasks is outside the scope of WakaTime. The most WakaTime will do for now is track automatic stats and report them. We will track time spent debugging and reading documentation, but for now it's just coding time.

To track time per task, you can use another task-based time tracking app and connect our api (https://wakatime.com/api/) to cross-reference logged time with tasks.
