### ISSUE TITLE
Need to move internal config into wakatime folder

### ISSUE THREAD

**Issue by Henvy-Mango** [wakatime/jetbrains-wakatime#261]
Might this jetbrains-wakatime plugin be same to the vscode-wakatime plugin in its functionality?
Move the internal config into wakatime folder like this commit
<https://github.com/wakatime/vscode-wakatime/commit/3b59e70ed9be4a52c6ce38ac19154ff8497f3ae4>

**Comment by alanhamlett** [comment]
Fixed in 4abeb4898fda02e219e1b9d649de4810c3ab338c and released in v14.2.0. Thanks!

**Comment by alanhamlett** [comment]
Oops, fixed in v14.2.1.
