### ISSUE TITLE
Plugin for JetBrains Fleet

### ISSUE THREAD

**Issue by artsuhov** [wakatime/jetbrains-wakatime#270]
Hello! 
Do you have a plan to add wakatime to JetBrains Fleet?
https://www.jetbrains.com/fleet/

**Comment by alanhamlett** [comment]
Sure, we would if they had a plugin api. Until then there's no way to build a plugin for Fleet.

**Comment by muety** [comment]
They do have a plugin dev API, see [here](https://www.jetbrains.com/help/fleet/building-custom-theme-plugins.html), Would love to see a WakaTime plugin for Fleet! 🙌

**Comment by SnowJunior** [comment]
I think they opened a plugin api that is now available. Is it possible to get the plugin on fleet @alanhamlett
