### ISSUE TITLE
Api key prompt with api_key_vault_cmd 

### ISSUE THREAD

**Issue by SamueleFacenda** [wakatime/jetbrains-wakatime#274]
I'm using `api_key_vault_cmd` instead of the plain `api_key` in my `.wakatime.cfg`. Every time I startup the IDE I get the insert-api-key prompt every n seconds.

**Comment by alanhamlett** [comment]
Fixed with d993278d934c35d5a43a1e4d5752461056855073 and released in v14.3.11.
