### ISSUE TITLE
Not restarting pycharm IDE

### ISSUE THREAD

**Issue by KubasuIvanSakwa** [wakatime/jetbrains-wakatime#276]
I am using kali linux I did Install my wakatime in pycharm but the wakatime time plugin cannot restart the IDE for the api key part, how can I resolve this

**Comment by alanhamlett** [comment]
The plugin shouldn't restart, PyCharm should prompt to restart after installing new plugins. If it doesn't you can restart your IDE manually by closing it.

Then go to `Tools → WakaTime Settings` to enter your api key.
