### ISSUE TITLE
Can't cancel key input

### ISSUE THREAD

**Issue by luckydonald** [wakatime/jetbrains-wakatime#279]
` ~/.wakatime/wakatime.log:` 
 ```
is empty
 ```
 
 
#  Steps to reproduce:
 
 1. Install JBrains plugin in an IDE (i.e. PyCharm)
 2. Don't have an API Key
 3. Restart the IDE  
 > <img width="538" alt="Screenshot 2024-03-30 at 19 00 53" src="https://github.com/wakatime/jetbrains-wakatime/assets/2737108/fac919bd-5cdd-4047-ba8d-b234f0b94c05">.   
 > This pops up
4. Click Cancel
4. Click Cancel
4. Click Cancel
4. Click Cancel
4. Click Cancel
4. Click Cancel
5. Repeat from step 4

# Expected Behavior
It cancels and I can deinstall the plugin

# Actual Behaviour

The same window pops up again and again if I press Cancel, 
seemingly stuck in a while loop until one enters an actual working key.

Thus blocking the IDE, rendering it unusable.

**Comment by alanhamlett** [comment]
Fixed in v14.3.13.
