### ISSUE TITLE
Configure `api_url` in `.wakatime.cfg`

### ISSUE THREAD

**Issue by Ritsuka314** [wakatime/jetbrains-wakatime#282]
Since `wakatime-cli` supports configuring the API base URL through the `--api-url` flag, and the key `api_url` is documented for `wakatime.cfg`, `ConfigFile.java` should be added a method `public static String getApiUrl()` which should then be used by `WakaTime.buildCliCommand`.

**Comment by alanhamlett** [comment]
Actually, this isn't necessary since `wakatime-cli` reads the config file on it's own and sets `api_url` without needing the IDE to pass `--api-url`. It's already handled by `wakatime-cli`.
