### ISSUE TITLE
Toolbar keep stuck at 0 seconds

### ISSUE THREAD

**Issue by mateusb12** [wakatime/jetbrains-wakatime#294]
**This is just an IDE display issue. My project time is correctly being tracked via API, and I already manually checked that on the official website.**

As you can see in the screenshot, it is always stuck at 0 seconds.

![waka_bug](https://github.com/user-attachments/assets/cd272767-9b51-4a69-b5ca-f2bf162e4d3c)

- **Already tried uninstalling the plugin, it did not work.**
- **Already tried uninstall the IDE, it did not work.**

**Comment by mateusb12** [comment]
![waka_bug](https://github.com/user-attachments/assets/673d1d2e-ccaf-4201-a065-271505a67268)

For some reason it started working again, I don't know why

**Comment by alanhamlett** [comment]
The api endpoint used by the status bar text is cached, so often the first time it updates after midnight in your time zone it can say `0 secs` for a while.
