### ISSUE TITLE
Redirect to correct dashboard on selfhosted systems when clicking the Statusbar Icon

### ISSUE THREAD

**Issue by Stenz123** [wakatime/jetbrains-wakatime#296]
The dashboard url is currently hard coded to wakatime.com [see in code](https://github.com/wakatime/jetbrains-wakatime/blob/62751608bd5aa6c81c85876b502ef9986f760e99/src/com/wakatime/intellij/plugin/WakaTime.java#L733C1-L735C6).
On a self-hosted system (when the `api_url` param is set) this will redirect to the wrong dashboard when clicking on the Statusbar Icon.
I am willing to fix this myself, but is it viable to parse the dashboard URL from the `api_url` option?

**Comment by gandarez** [comment]
Api url is used by the wakatime cli to call the backend whereas this hardcoded opens the dashboard.

**Comment by Stenz123** [comment]
But if you parse the api_url string and use the part in front of the /api and replace it with /dashboard instead?

**Comment by Stenz123** [comment]
Another approach to solve this issue could be to add another config option which specifies the dashboard url.
