### ISSUE TITLE
Crash in Android Studio Installation on Win XP jdk 1.7

### ISSUE THREAD

**Issue by wagfeliz** [wakatime/jetbrains-wakatime#30]
Its an virtualbox xp 64 machine.
The setup loads, gives the welcome screen, shows the select components screen, and when I press next button when it supouse to show the licence agreement, it crashs.

The error on event view :
The application, X:\EclipseAndroid\android-studio-bundle-141.1890965-windows.exe, generated an application error The error occurred on 05/03/2015 @ 13:29:45.599 The exception generated was c0000005 at address 000000006B006369 (wow64!Wow64LdrpInitialize)

Obs: I tried to unstall and re-install java sdk jdk-7u79-windows-x64.exe with no sucess. Also tried to put on path, java_home, sdk_home info about this sdk but it dosent seens to have any effect.
Obs2: I also tried to do this installation in another virtual machine, same error.
Obs3: I also tried to copy the exe installation into a local directory, same error.

Thats odd, do anyone have any idea ?

**Comment by alanhamlett** [comment]
This is when installing the WakaTime plugin or when installing IntelliJ?

**Comment by wagfeliz** [comment]
Android Studio. I found interesting that in the site it says windows xp is not listed as supported anymore... Also, I tried to install in a phisical machine ( not virtual ), and got error also.

**Comment by alanhamlett** [comment]
Oh, I'm not the maintainer of Android Studio. You would have better luck creating an issue at http://developer.android.com/support.html
