### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by MadMind** [wakatime/jetbrains-wakatime#33]
The plugin causes the editor to freeze very often. That causes really bad experience.
Could you please run CLI client in a separate thread or something like this to prevent editor freezes.

**Comment by alanhamlett** [comment]
What's the value of `debug` in your `~/.wakatime.cfg` file?

**Comment by DavidFrahm** [comment]
@alanhamlett I've noticed you ask this before. How does this happen, that people get debug=true in their config file?

**Comment by alanhamlett** [comment]
@DavidFrahm by default it's set to false, so they set it to true by editing the config file.

**Comment by MadMind** [comment]
@alanhamlett debug=false

**Comment by alanhamlett** [comment]
Should be fixed with 946d8c5d59587ccce9b2026e2e22b17094e05024.

**Comment by MadMind** [comment]
Yes, this did solve the issue.
Thanks!
