### ISSUE TITLE
PhpStorm on mac freeze sometimes

### ISSUE THREAD

**Issue by petrgrishin** [wakatime/jetbrains-wakatime#36]
What steps will reproduce the problem?
1. Open project in PhpStorm
2. Open php file
3. Make some changes
5. FREEZE

https://youtrack.jetbrains.com/issue/WI-27410

**Comment by DsXack** [comment]
:+1:

**Comment by elfelrandcor** [comment]
:+1:

**Comment by petrgrishin** [comment]
:+1:

**Comment by alanhamlett** [comment]
This traceback is showing line numbers from v4.0.9 of the WakaTime plugin. It should be fixed by upgrading the plugin to v4.0.10.

**Comment by DsXack** [comment]
Thanks. v4.0.10 does not freeze

**Comment by petrgrishin** [comment]
Thanks

**Comment by alanhamlett** [comment]
Yep, sorry about that bug in 4.0.9 release.
