### ISSUE TITLE
Renaming a project isn't taken into account properly

### ISSUE THREAD

**Issue by daften** [wakatime/jetbrains-wakatime#39]
When I rename a project, it is considered a new project on Wakatime. Instead, I'd think it should update the online name of the project, so the new metrics are against the same project.

**Comment by gandarez** [comment]
@alanhamlett could you confirm if this behaviour still happens?

**Comment by alanhamlett** [comment]
If you rename a project from the dashboard on the website, then it correctly renames all past code stats. Any new stats with the old project name will re-create the old project going forward, unless you create a Custom Rule to always rename the project.
