### ISSUE TITLE
Wrong programming language recognition

### ISSUE THREAD

**Issue by JogahCR** [wakatime/jetbrains-wakatime#41]
Hi Wakatime Team!

I've been using Wakatime on Android Studio since a couple of weeks now and just noticed that a lot of time spend on JAVA files (.java) are categorised as Python on the Wakatime dashboard.

![screen_shot_2015-06-17_at_10_15_12_am](https://cloud.githubusercontent.com/assets/2111608/8212684/3cca3fe8-14da-11e5-94e2-7f18146e4fb9.png)

**Comment by alanhamlett** [comment]
That was a temporary issue with language detection, but it's fixed now.
