### ISSUE TITLE
PyCharm Error : WT requires Python to be installed

### ISSUE THREAD

**Issue by ireneu** [wakatime/jetbrains-wakatime#43]
Python 3.4 is already installed on the machine, but the error appears every time PyCharm is launched.

![screen shot 2015-07-01 at 15 56 01](https://cloud.githubusercontent.com/assets/8791107/8456145/bfbf663c-2009-11e5-8d51-43147d74b903.png)

**Comment by alanhamlett** [comment]
What is the installation location of Python on your machine?

**Comment by ireneu** [comment]
In /usr/local/Frameworks/Python.framework/Versions/3.4/bin/ (HomeBrew installation)

**Comment by alanhamlett** [comment]
what happens when you run this command in terminal:

`pythonw --version`

and also:

`python --version`

**Comment by ireneu** [comment]
`pythonw: command not found`

`python --version` shows `   Python 3.4.3`

**Comment by ireneu** [comment]
Resolved: `python` was just an alias in my terminal sessions, but there was no symlink. Just created a symlink and wakatime asked for my API key when starting PyCharm.

Thanks a lot for taking your time!

**Comment by alanhamlett** [comment]
Awesome!
