### ISSUE TITLE
Wrong menu item position

### ISSUE THREAD

**Issue by o-nix** [wakatime/jetbrains-wakatime#48]
I believe that every `Exit` menu item should be at the bottom in every application. :smiling_imp:
But at the moment I see annoying `WakaTime API Key` item *after* `Exit`.

**Comment by vysinsky** [comment]
I personally think it should not be in File menu at all. Settings window is better place :)

**Comment by o-nix** [comment]
:+1:

**Comment by dlsniper** [comment]
I'd rather see this under Tools menu or under Settings -> Other Tools than in the File menu.

**Comment by alanhamlett** [comment]
Different platforms have the Settings menu in different locations, so moved it to the bottom of the Tools menu.
