### ISSUE TITLE
Android Studio Wakatime: Error: Missing API Key

### ISSUE THREAD

**Issue by sayo9394** [wakatime/jetbrains-wakatime#49]
After installing the plugin, by following https://wakatime.com/help/plugins/android-studio, and after entering the key after restart, the app refuses to track info from Android Studio.
Enabling debug produces the following log. I have uninstalled and reinstalled multiple times, making sure i delete all instances of wakatime, all with no success... 
Going to File -> WakaTime API Key confirms that the key has been entered correctly.

I have installed the Sublime Text plugin, and it all works brilliantly! 

![idea_sample](https://cloud.githubusercontent.com/assets/321680/10095729/32a497ec-63af-11e5-842b-989c71fcb73d.png)

Cheers,
Simon

**Comment by alanhamlett** [comment]
Looks like Android Studio read the api key from `~/.wakatime.cfg` but wakatime cli wasn't able to read the api key. I'll start passing the api key to wakatime cli and release the fix in the morning.

**Comment by alanhamlett** [comment]
I wasn't able to reproduce the error on a Windows VM, but the latest version of the plugin should work.
