### ISSUE TITLE
update to v503 stops working

### ISSUE THREAD

**Issue by dleffler** [wakatime/jetbrains-wakatime#52]
After updating PhpStorm 9.0.2 to Wakatime v5.0.3, the plugin no longer works due to a complaint about Python not being installed.  I am using Win 7 x64 and ActiveState Python 2.7...which worked until now.

Python is in my PATH, but doesn't seem to use the registry keys you're (now) looking for?

**Comment by alanhamlett** [comment]
Sorry about that, it's fixed in v5.0.4.
