### ISSUE TITLE
Can't install wakatime in rubymine

### ISSUE THREAD

**Issue by mhenrixon** [wakatime/jetbrains-wakatime#55]
Keep getting connection timeout. Any ideas why that might happen?

**Comment by alanhamlett** [comment]
Maybe it's related to this bug? https://youtrack.jetbrains.com/issue/IDEA-130953

If not, can you create an issue for Jetbrains to fix it here: https://youtrack.jetbrains.com/issues/IDEA

**Comment by alanhamlett** [comment]
Let me know if I should re-open this issue.
