### ISSUE TITLE
Not sending logs from android studio

### ISSUE THREAD

**Issue by sumitacharyalives** [wakatime/jetbrains-wakatime#59]
i installed plugin and entered api key also but its not showing anything on dashboard.

**Comment by alanhamlett** [comment]
First, can you install Python from https://www.python.org/downloads/

That might be the problem, but can you still check your idea.log file for WakaTime related error messages?

**Comment by sumitacharyalives** [comment]
i tried by installing python but no success, its still not showing anything there.

**Comment by alanhamlett** [comment]
Are there any error messages in your `idea.log` file? To find your `idea.log` file follow [these instructions](https://intellij-support.jetbrains.com/hc/en-us/articles/206827517-Locating-IDE-log-files).

**Comment by sumitacharyalives** [comment]
[Log.txt](https://github.com/wakatime/jetbrains-wakatime/files/46475/Log.txt)

**Comment by sumitacharyalives** [comment]
please find log file, i sent above.

**Comment by alanhamlett** [comment]
We need to turn on debug mode to get more info from your `idea.log` file. Here's instructions for turning on debug mode:
https://github.com/wakatime/wakatime#troubleshooting
After that, can you send the new `idea.log` file along with your `~/.wakatime.log` file to my email?

**Comment by sumitacharyalives** [comment]
Regards
Sumit Acharya

**Comment by alanhamlett** [comment]
Please email the logs to alan@wakatime.com, since github doesn't attach them here.

**Comment by sanjogshrestha** [comment]
I also facing same issue. I am currently using AS 2.1.1. I  have sent you the log report. Please have a look into it!

**Comment by alanhamlett** [comment]
@sanjogshrestha was a bug caused when editing a file without an open project. It's fixed now in v7.0.4. You can upgrade by going to the Plugins menu inside Android Studio Settings and clicking the WakaTime plugin, then the upgrade button.
