### ISSUE TITLE
Where do I set the API key? (IntelliJ Idea)

### ISSUE THREAD

**Issue by Gurpartap** [wakatime/jetbrains-wakatime#60]
v6.0.1

Instructions say relaunch IDE and enter API key. I can't find a field to put it into. Searched the menu, as well as Preferences.

My key's set in `~/.wakatime.cfg` from other tools' installation, if it matters.

**Comment by vysinsky** [comment]
Hi, I don't know where IntelliJ Idea has it, but in the latest PhpStorm it is under `Tools -> WakaTime API Key` - or just pres double shift and type wakatime.

**Comment by Gurpartap** [comment]
Thanks! Apparently, it automatically picked the key from the `~/.wakatime.cfg` file.

**Comment by didagu** [comment]
This same thing happened to me too. I switched from VS code to Webstorm and I was not prompted to input the key after installing the plugin. However Webstorm picked the key already from `~/.wakatime.cfg` file.
In my opinion, perhaps it should be mentioned somewhere in the documentation; in order to avoid such occurrence again.

**Comment by gandarez** [comment]
I agree, it should be more clear for the users to not get confused.

**Comment by apocsve** [comment]
As @didagu I agree should be added into the documentation, I relaunched the app multiple times. (turn on and off again haha)

**Comment by egbodofo** [comment]
To set Wakatime key for Pycharm, from the GUI click on Tools->Wakatime Settings and input API key

**Comment by alanhamlett** [comment]
It's currently mentioned in the black question mark circle tooltip, when hovering your mouse over the icon:

https://wakatime.com/intellij-idea

**Comment by MRJAHID** [comment]
> Hi, I don't know where IntelliJ Idea has it, but in the latest PhpStorm it is under `Tools -> WakaTime API Key` - or just pres double shift and type wakatime.

Thanks Man!!

**Comment by Njoxpy** [comment]
> Hi, I don't know where IntelliJ Idea has it, but in the latest PhpStorm it is under `Tools -> WakaTime API Key` - or just pres double shift and type wakatime.

Thanks, I was having the same issue!
