### ISSUE TITLE
Android Studio - WakaTime threw an uncaught UnknownHostException

### ISSUE THREAD

**Issue by brunjick** [wakatime/jetbrains-wakatime#64]
WakaTime threw an uncaught UnknownHostException - this exception is thrown when there is no network connection at launch. I wonder, does wakatime plugin work in offline after this exception?

**Comment by alanhamlett** [comment]
That caused the plugin to re-download wakatime-core, deleting the old one first, which breaks offline logging. It's fixed in v6.0.4 released today.

**Comment by brunjick** [comment]
Removed and reinstalled plugin (v6.0.4), but same happens
`8:02:41 PM Plugin Error: WakaTime threw an uncaught UnknownHostException. Disable Plugin`
`8:02:41 PM UnknownHostException: raw.githubusercontent.com`

**Comment by brunjick** [comment]
Just checked out your commit, looks like you are logging exception even though it's caught and it doesn't break tracking. But I think this practice is bad, because IDE offers to disable plugin and feels like something is broken

**Comment by alanhamlett** [comment]
Just released v6.0.5 where all errors are now logged as warnings.
