### ISSUE TITLE
Setting a time parameter

### ISSUE THREAD

**Issue by domface** [wakatime/jetbrains-wakatime#66]
Is there any way to set a time parameter that tells the IDE to keep sending heartbeats, even after key typing has stopped, or perhaps send heartbeats as the IDE is active? I noticed on the XCode IDE, the IDE sends heartbeats even as i am scrolling through code, not necessarily typing anything. This would come in handy when I go to bill my customers, when I spend most of the day reading through someone else's code and trying to understand how something works, before writing anything.

**Comment by alanhamlett** [comment]
We should find an event hook that we can bind to for scrolling/activity to send heartbeats when reading code.

**Comment by alanhamlett** [comment]
Fixed with d289d068804689cff931feca388a689f874e744c.
