### ISSUE TITLE
Linux unstability

### ISSUE THREAD

**Issue by Pyton** [wakatime/jetbrains-wakatime#70]
When I'm making search and replace lot of files Wakatime kills My computer. It consumed whole memory (12GB on board) and 100% CPU usage (i7 8 thread).

Once I could start Htop i saw many python wakatime process.

Many file means more than 200.
Last time i replaced ~2000 files, system stops responding.
After turning off plugin the same files were replaced in ~2s.

I'm using xubuntu 15.10 with i3wm

**Comment by alanhamlett** [comment]
Which version of the plugin are you using?

**Comment by Pyton** [comment]
6.0.7

**Comment by alanhamlett** [comment]
How's the latest version on Linux?

**Comment by Pyton** [comment]
Now i updated to 7.0.4 and looks good.

**Comment by alanhamlett** [comment]
Awesome!
