### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode by 0xc8 in position 54

### ISSUE THREAD

**Issue by bitqiang** [wakatime/jetbrains-wakatime#72]
并且在  wakaTime Setting 里面看见设置的API key是正确的。

**Comment by alanhamlett** [comment]
Copy it from:
https://wakatime.com/settings
Then paste into Jetbrains via the Tools -> WakaTime Settings menu.

**Comment by bitqiang** [comment]
I have correctly pasted my API, but can not use , I have tried to replace the api, and webstorm also updated the new api, but still can not afford . Also tried to uninstall wakatime, then reload, too.

**Comment by alanhamlett** [comment]
Do you have an error message in your `~/.wakatime.log` or `idea.log` file?

**Comment by bitqiang** [comment]
[This is an error  message](http://7xsjto.com1.z0.glb.clouddn.com/QQ%E5%9B%BE%E7%89%8720160731103908.png)

**Comment by alanhamlett** [comment]
What's the full path of the file you were editing when that error occured?

**Comment by alanhamlett** [comment]
Also, can you replace line `129` in file `C:\Users\chuli\AppData\Roaming\WakaTime\wakatime-master\wakatime\stats.py` with:

`if os.path.exists(filepart + '.c') or os.path.exists(filepart + '.C'):`

Then see if the error is fixed?

**Comment by alanhamlett** [comment]
@isortegah this seems related to the issue you were having with eclipse-wakatime.

**Comment by gandarez** [comment]
Is this still NOK @alanhamlett?

**Comment by alanhamlett** [comment]
@bitqiang is this error still happening? Closing for now until getting more info.
