### ISSUE TITLE
Wakatime Settings for API key does not show up in CLion.

### ISSUE THREAD

**Issue by Entalpi** [wakatime/jetbrains-wakatime#74]
I have the latest Wakatime plugin in the latest CLion release (2016.2) and the settings for entering the API does not show up. I might be doing something wrong in that case I am so sorry for wasting your time. :/
![screen shot 2016-08-02 at 13 44 04](https://cloud.githubusercontent.com/assets/1652130/17327285/386de6bc-58b7-11e6-89bd-ccb275601930.jpg)

**Comment by alanhamlett** [comment]
It's under the Tools -> WakaTime settings menu.

<img width="1128" alt="screen shot 2016-08-02 at 2 12 38 pm" src="https://cloud.githubusercontent.com/assets/522344/17328003/7b8bca78-58bb-11e6-986b-25597f6bc601.png">

**Comment by Entalpi** [comment]
Dear God, thank you @alanhamlett!

**Comment by clemf** [comment]
@alanhamlett FYI the documentation for the PHPStorm version simply says "Enter your API key" without saying where.

**Comment by alanhamlett** [comment]
Yep, to keep the instructions simple and because usually PHPStorm will prompt you for the api key if it's not already entered.

**Comment by clemf** [comment]
Not sure why, but it didn't prompt for me and I was very confused. Had to search issues to find out where the option to enter the key was.

**Comment by Entalpi** [comment]
@clemf Exactly my experience.
