### ISSUE TITLE
Mixed sending of project and directory name from PhpStorm

### ISSUE THREAD

**Issue by fulopattila122** [wakatime/jetbrains-wakatime#75]
Hello,

I've been having this issue for a while.
Here's an example:
I have a project called `lssapps.com` in the folder `src`:

![image](https://cloud.githubusercontent.com/assets/1162360/17767162/72d413b2-6537-11e6-8a07-b299573389ee.png)

Working with that single project results in logging for both "projects" **lssapps.com** and **src**:

![image](https://cloud.githubusercontent.com/assets/1162360/17767297/1c01bc46-6538-11e6-8865-90370d71e6c7.png)

I don't know if it's me doing something nasty or some kind of bug, but I'd expect to only log time for the project name **lssapps.com** and no log to **src** at all. Not to mention that most of my projects are in a folder called src, so I have this garbage project in Wakatime that permantently collects time snippets.

**Comment by alanhamlett** [comment]
This could happen when editing a file without the project open, because WakaTime uses the directory from revision control if the IDE does not give a project name.

If you're always editing files within the project, then it could be the plugin has a bug and sometimes doesn't see the project name.

**Comment by fulopattila122** [comment]
Thanks for looking into it Alan. I don't believe I have opened a file without the project open (it was a single PhpStorm session with the project permanently open). PhpStorm is the only app in my system reporting to WakaTime.

![image](https://cloud.githubusercontent.com/assets/1162360/17768601/53460374-653d-11e6-9122-c250806df662.png)

![image](https://cloud.githubusercontent.com/assets/1162360/17768605/59849a70-653d-11e6-9761-5999c938e07c.png)

Also the files edited during report to `src` are part of the project. As an additional info there was some idle time away from PhpStorm during the session above.

That's why I presume there might be a problem in the plugin not seeing the project name.

**Comment by fulopattila122** [comment]
It also shows up in the daily E-mail reports:

![image](https://cloud.githubusercontent.com/assets/1162360/17923024/ac22cb42-69ea-11e6-92e1-508afc0266af.png)

It was a single project I was working on, except for that 1 minute of *concordtest*.

I'm open to dig deeper if you tell me where to start.

**Comment by alanhamlett** [comment]
Just released a new version 7.0.9 that uses the last project if one failed to be detected (aac3fe8c7d6509de4e88c16c73424db13d833f39). Can you update and see if it's fixed?

**Comment by fulopattila122** [comment]
Thanks a lot, I've updated it, I'll keep using it today, and see if the problem goes away.

**Comment by fulopattila122** [comment]
Great, now the logs are excellent! Thank you for the quick help :bow:
