### ISSUE TITLE
Wakatime python process uses too much memory/cpu

### ISSUE THREAD

**Issue by AAverin** [wakatime/jetbrains-wakatime#76]
When I was experiencing some memory and cpu problems in general on my MacBook Pro (top version) I was browsing thorough task manager and noticed a few Python processes running, one of which was consuming significant amount of memory.
I don't remember exact values.

Going into details of that python process led me to Wakatime plugin in my Android Studio.
Uninstalling the plugin resolved the issue.

**Comment by KlausGroenbaek** [comment]
I have the same issue, 3 python processed using <95% CPU. Strangle I have been using the plugin for more than a month before this issue started. My guess is that it is related to very large Json and csv files that are now in the root of my project folder. if thats the case there should probably a fail safe that excludes files that are larger than 2.5MB as with intelliJ Find-In-Files.

**Comment by alanhamlett** [comment]
Are you editing those large files in IntelliJ? The python process does count the number of lines in the current file that you are editing.

**Comment by KlausGroenbaek** [comment]
Intellij only loads the first 2.5MB, and has disabled editing, but the only change to the project in the last 2 days, is the two JSON large files (48/60MB). Both files have extremely long lines (intellij soft wraps), because they contain arrays of 4-6 million floats without line breaks.

**Comment by alanhamlett** [comment]
Without opening those large JSON files in IntelliJ, WakaTime won't read them either. Just having them in your project folder won't cause slowness. When you notice the slowness, can you run this command to see which file is causing it:

`ps -ef | grep wakatime`

It's possible that a build tool or other plugin is triggering a write to that file even if you're not editing it yourself, which could cause the slowness. I'll update the plugin today to turn off the line count for large files.

**Comment by alanhamlett** [comment]
Fixed now that we're using the new Go wakatime-cli.
