### ISSUE TITLE
Improve branch filtering

### ISSUE THREAD

**Issue by Tuurlijk** [wakatime/jetbrains-wakatime#78]
![2016-10-24_ _wakatime](https://cloud.githubusercontent.com/assets/790979/19851131/a62d9b0c-9f5c-11e6-9324-49739038041f.png)

I can see I worked a total amount of time on all these branches in the project. But I would like to see how many hours I have worked per branch. This is because we use a single branch per ticket in our setup.

Currently I need to click away all branches I don't want to see to get to that point.

I would love to be able to 'zoom in' on a single branch wit a single click.

**Comment by alanhamlett** [comment]
Great idea! I've moved this to the main repo for tracking plugin independent issues:

wakatime/wakatime#68
