### ISSUE TITLE
Android Studio 2.2.2 wakatime setup error.

### ISSUE THREAD

**Issue by abdulgaffarabu** [wakatime/jetbrains-wakatime#79]
I installed python-3.6.0b3-amd64.exe and added path in environment variables, then restarted android studio. but still the following error occurs.

This is the actual error:

WakaTime requires Python to be installed.
You can install it from https://www.python.org/downloads/
After installing Python, restart your IDE.

**Comment by alanhamlett** [comment]
What happens when you open a cmd prompt and type `pythonw --version`?

**Comment by abdulgaffarabu** [comment]
'pythonw' is not recognized as an internal or external command,
operable program or batch file.

**Comment by alanhamlett** [comment]
That means Python isn't in your PATH. Once the output of that cmd is a version number, WakaTime will be able to find Python too.

**Comment by arjava** [comment]
on new android studio 3.2 error, a message appears to not activate the wakatime plugin

**Comment by alanhamlett** [comment]
@arjava is that the update plugin message? Clicking `update` will fix that.

<img width="480" alt="update-plugin" src="https://user-images.githubusercontent.com/522344/47105050-bf374d80-d1f7-11e8-88f0-821e150d2eae.png">

**Comment by arjava** [comment]
![screen shot 2018-10-21 at 13 01 21](https://user-images.githubusercontent.com/21032373/47263735-ae594580-d531-11e8-9b9a-9c2dcc73db9e.png)

I got this message after installing again sir

**Comment by gandarez** [comment]
Is this still NOK @alanhamlett?

**Comment by alanhamlett** [comment]
Closing since we no longer depend on Python anymore.
