### ISSUE TITLE
Files logged in wrong project

### ISSUE THREAD

**Issue by Gianlu01** [wakatime/jetbrains-wakatime#81]
I have noticed that some files get logged in the wrong project. I'm pretty sure those files aren't coming in any way from the project currently in use, it is possible they're coming from a project opened in another window on AndroidStudio. Don't know if it's just me and/or if it's mine fault.

Thanks

**Comment by jel3mediasolve** [comment]
This is happening for me as well.

**Comment by alanhamlett** [comment]
Fixed in v9.0.0.
