### ISSUE TITLE
Typoscript

### ISSUE THREAD

**Issue by juancarloscruzd** [wakatime/jetbrains-wakatime#83]
I hace have this in my report, think is a bad mapping issue.

![image](https://cloud.githubusercontent.com/assets/1282781/23129147/8ffcadb4-f74f-11e6-8501-121ee67ff853.png)

**Comment by alanhamlett** [comment]
Would you be able to share the contents of a `.ts` file that was incorrectly detected as `TypoScript` to help improve language detection? You could email it to me as a secret gist or paste it here if it's not private.

**Comment by alanhamlett** [comment]
Should be fixed with v8.0.0 released today.
