### ISSUE TITLE
“WakaTime requires Pyhton to be installed” after WebStorm update

### ISSUE THREAD

**Issue by authenticsebastian** [wakatime/jetbrains-wakatime#84]
After updating WebStorm to 2016.3.4 I started getting this message on start:

![2017-03-13 09_16_38-agstaticresources - c__repo_agstaticresources - _agstaticresources_ag-js_ro](https://cloud.githubusercontent.com/assets/17334889/23846464/e629ff82-07cd-11e7-8f46-4a502da70b54.png)

The practical effect is that WakaTime ceased to report time spent on coding. I installed Python from the link in message but it didn’t help.

**Comment by authenticsebastian** [comment]
I’m learning how to live without WakaTime. And that’s dangerous situation for WakaTime.

**Comment by alanhamlett** [comment]
Lol, sorry for taking so long. Let's turn on debug mode and check your `idea.log` file to see any error messages encountered when detecting/downloading Python:
https://github.com/wakatime/jetbrains-wakatime#troubleshooting

**Comment by authenticsebastian** [comment]
Okay got. Want me to paste here everything? It’s longish.

But before answering that, let me take a guess (what every ticked assigned person loves, I know) that problem might be here:

```
2017-03-16 11:26:38,444 [   8950]  DEBUG -                       WakaTime - C:\Users\Sebastian Cholewa\AppData\Roaming\WakaTime\python\pythonw --version 
2017-03-16 11:26:38,445 [   8951]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "C:\Users\Sebastian": CreateProcess error=193, %1 is not a valid Win32 application
```

And after that there is a series of

```
2017-03-16 11:26:38,525 [   9031]  DEBUG -                       WakaTime - \Python50\pythonw\python --version 
2017-03-16 11:26:38,526 [   9032]  DEBUG -                       WakaTime - java.io.IOException: Cannot run program "\Python50\pythonw\python": CreateProcess error=2, The system cannot find the file specified 
```

Just with different numbers.

The space in user’s folder? (I tried to change it to test my theory but Windows does not allow that.) Because file is there:

![image](https://cloud.githubusercontent.com/assets/17334889/23992931/0a7f4bd0-0a3f-11e7-8ab8-c4bfd887239c.png)

**Comment by alanhamlett** [comment]
> Want me to paste here everything?

Yes, or you can email the full log to alan@wakatime.com

We should be seeing some debug logs showing Python being  downloaded and extracted into `C:\Users\Sebastian Cholewa\AppData\Roaming\WakaTime\python`. Something strange is why that `pythonw.exe` already there isn't able to be run. Possibly python was corrupted when downloading/extracting, so can you try deleting this directory before restarting WebStorm:

`C:\Users\Sebastian Cholewa\AppData\Roaming\WakaTime`

**Comment by authenticsebastian** [comment]
I sent log via email.

I deleted `WakaTime` folder but there was no difference after opening the application. Stil wanted to open program `"C:\Users\Sebastian"`.
