### ISSUE TITLE
Can't find plugin in directory

### ISSUE THREAD

**Issue by Edisoni** [wakatime/jetbrains-wakatime#87]
![2017-04-16 22 42 12](https://cloud.githubusercontent.com/assets/10086099/25073762/fd735c2c-22f5-11e7-8345-f6328140a8ec.png)

**Comment by alanhamlett** [comment]
Make sure to click the `Browse repositories...` button to find user-contributed plugins. Clicking `Install Jetbrains Plugin` won't show the WakaTime plugin. I've added an animated gif to help here:

https://github.com/wakatime/jetbrains-wakatime#installation
