### ISSUE TITLE
Allow treating sub-folders matching a pattern as projects

### ISSUE THREAD

**Issue by vjpr** [wakatime/jetbrains-wakatime#90]
When using a monorepo (e.g. using https://github.com/lerna/lerna), there may be multiple packages in an IntelliJ project. I would like to differentiate between them. What is the best way to do this?

I have looked at `projectmap` in the `ini`, and https://wakatime.com/faq#rename-projects, and https://github.com/wakatime/wakatime/blob/master/wakatime/projects/projectmap.py#L6 but I can't seem to figure it out...

**Comment by vjpr** [comment]
Figured it out...

**~/.wakatime.cfg**

```ini
[projectmap]
packages/((?:@(?:\w)+/)?(?:[\w\-.]+))
```

View regex on [pythex](
https://pythex.org/?regex=packages%2F((%3F%3A%40(%3F%3A%5Cw)%2B%2F)%3F(%3F%3A%5B%5Cw%5C-.%5D%2B))&test_string=packages%2F%40foo%2Fbar-1%2Fbaz%0Apackages%2Fbar-1%2Fbaz&ignorecase=0&multiline=0&dotall=0&verbose=0)

**Comment by peterjcole** [comment]
This solution didn't work for me - not sure what I'm missing? I have a lerna repo with different projects in the `packages` directory which ideally would like to show up as separate projects.

I don't understand the syntax for `[projectmap]` (what do the curly braces mean?) and it's not really documented sadly.

I added rules in the web interface for now to rename the main ones I care about individually but would rather not have to do that every time.

@alanhamlett hope you don't mind me tagging you, I'm not really sure what the Github etiquette is for when an issue is closed so please let me know if I've done something I should never do 😄

**Comment by alanhamlett** [comment]
> This solution didn't work for me

What's your config (minus api key) look like, and what folder is your project located at?

> I don't understand the syntax for [projectmap] (what do the curly braces mean?) and it's not really documented sadly.

The square brackets mean `[projectmap]` is an INI config section. It's a way to group any `key = value` settings below the section under the section's name.

> @alanhamlett hope you don't mind me tagging you, I'm not really sure what the Github etiquette is for when an issue is closed so please let me know if I've done something I should never do

Tagging me isn't needed on closed issues. I'm already watching the repo so I get a notification for any comment, but no harm caused and mentioning me doesn't result in any extra notification.
