### ISSUE TITLE
this package is bad for phpstorm 2017.2 and phpstorm 2017.3, loot at the pic

### ISSUE THREAD

**Issue by oknixus** [wakatime/jetbrains-wakatime#91]
I always worked with phpstorm, but the time record is not right. Yesterday it's 0.
![image](https://user-images.githubusercontent.com/4592706/32584942-e0b704f2-c535-11e7-8c58-e551bccf7b53.png)

I like the package, but it's not work often.
Please fix it, you are great!
Thank you a lots.

By the way, my os is macOS High Sierra.

**Comment by alanhamlett** [comment]
Closing for now. Will re-open this issue if we can get debug logs reproducing the issue:
https://github.com/wakatime/jetbrains-wakatime#troubleshooting
