### ISSUE TITLE
Android studio 3.X can't get data

### ISSUE THREAD

**Issue by ArnoFrost** [wakatime/jetbrains-wakatime#94]
There're have been months that wakatime can't get data from AndroidStudio since 3.X.
So, every week I'll receive the email which told me I need to code everyday, truly I've already code everyday,whatever I reinstall the plugin or use debug mode. This plugin is every helpful, and I'm expecting your fix. thank you.

**Comment by alanhamlett** [comment]
After turning on debug mode, are there any error messages in your `~/.wakatime.log` file?
https://github.com/wakatime/jetbrains-wakatime#troubleshooting

**Comment by tariqywsf** [comment]
i have the same problem as ArnoFrost, and there is no error messages in my ~/.wakatime.log file.. just the Api Key and Debug set to true
i am using windows 10 pro 64bit
 Android Studio 3.3.2
Build #AI-182.5107.16.33.5314842, built on February 16, 2019
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by gandarez** [comment]
Is this still NOK @alanhamlett?

**Comment by alanhamlett** [comment]
Without more info, there's not much we can do to fix this. Closing for now.
