### ISSUE TITLE
Permanently: Waka Time in DEBUG mode

### ISSUE THREAD

**Issue by AlphRaue** [wakatime/jetbrains-wakatime#98]
After the upgrade to PHPStorm 2017.3.4 : PHPStorm reinstalled, all updates installed, WakaTime deleted and newly .integrated. No improvement. Why?.
![bwgl_2018 01 22_06h03m56s_001_debug](https://user-images.githubusercontent.com/18100563/35698996-04bb757c-078f-11e8-836f-fd6326a7cce9.png)

**Comment by alanhamlett** [comment]
To turn off debug mode, un-check the box in `Tools -> WakaTime Settings`.

**Comment by OysterD3** [comment]
> To turn off debug mode, un-check the box in `Tools -> WakaTime Settings`.

I don't have this option

**Comment by alanhamlett** [comment]
You can also manually edit `~/.wakatime.cfg` and remove the `debug = true` line.

**Comment by BartKim-J** [comment]
@alanhamlett Thank, it works for me
