### ISSUE TITLE
WakaTime (9.0.1) caused proxy issue

### ISSUE THREAD

**Issue by PeterLinBiz** [wakatime/jetbrains-wakatime#99]
WakaTime (9.0.1) caused proxy issue as the screenshot below.
When I disabled WakaTime (9.0.1), the issue was resolved.

![image](https://user-images.githubusercontent.com/16478162/36155937-b51430b8-10a3-11e8-8a37-acf63a50c05f.png)

![image](https://user-images.githubusercontent.com/16478162/36155966-ca7d8b02-10a3-11e8-96b5-e87644c8f90c.png)

![image](https://user-images.githubusercontent.com/16478162/36155996-dd1d150c-10a3-11e8-86ca-028613ffe3f4.png)

**Comment by gandarez** [comment]
Was that fixed @alanhamlett?

**Comment by alanhamlett** [comment]
This was fixed with fa12d4ce0c922057f644253279a8701139385808.
